/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => EnhancedCanvas
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// node_modules/monkey-around/dist/index.mjs
function around(obj, factories) {
  const removers = Object.keys(factories).map((key) => around1(obj, key, factories[key]));
  return removers.length === 1 ? removers[0] : function() {
    removers.forEach((r) => r());
  };
}
function around1(obj, method, createWrapper) {
  const inherited = obj[method], hadOwn = obj.hasOwnProperty(method), original = hadOwn ? inherited : function() {
    return Object.getPrototypeOf(obj)[method].apply(this, arguments);
  };
  let current = createWrapper(original);
  if (inherited)
    Object.setPrototypeOf(current, inherited);
  Object.setPrototypeOf(wrapper, current);
  obj[method] = wrapper;
  return remove;
  function wrapper(...args) {
    if (current === original && obj[method] === wrapper)
      remove();
    return current.apply(this, args);
  }
  function remove() {
    if (obj[method] === wrapper) {
      if (hadOwn)
        obj[method] = original;
      else
        delete obj[method];
    }
    if (current === original)
      return;
    current = original;
    Object.setPrototypeOf(wrapper, inherited || Function);
  }
}

// src/CanvasExploder.ts
var import_obsidian2 = require("obsidian");

// src/utils.ts
var import_obsidian = require("obsidian");
function isVersionNewer(currentVersion, oldVersion) {
  if (!currentVersion || !oldVersion)
    return false;
  if (currentVersion === oldVersion)
    return false;
  const current = currentVersion.split("-")[0].split(".").map(Number);
  const old = oldVersion.split("-")[0].split(".").map(Number);
  for (let i = 0; i < 3; i++) {
    const v1 = current[i] || 0;
    const v2 = old[i] || 0;
    if (v1 > v2)
      return true;
    if (v1 < v2)
      return false;
  }
  return false;
}
function randomId(length = 16) {
  const byteLength = Math.ceil(length / 2);
  const array = new Uint8Array(byteLength);
  window.crypto.getRandomValues(array);
  return Array.from(
    array,
    (byte) => byte.toString(16).padStart(2, "0")
  ).join("").substring(0, length);
}
var TagQueryParser = class {
  /**
   * Parses a query string into a TagQuery structure.
   * Example: "#a #b -#c OR #d" -> [ {include: ["#a", "#b"], exclude: ["#c"]}, {include: ["#d"], exclude: []} ]
   */
  static parse(input) {
    if (!input.trim())
      return [];
    const groups = input.split(/(?:\s+|^)OR(?:\s+|$)|\|/i);
    const query = [];
    for (const groupStr of groups) {
      const trimmedGroup = groupStr.trim();
      if (!trimmedGroup)
        continue;
      const whitespaceTokens = trimmedGroup.split(/\s+/);
      const group = { include: [], exclude: [] };
      for (let wToken of whitespaceTokens) {
        if (!wToken)
          continue;
        if (wToken.toUpperCase() === "AND")
          continue;
        let isExclude = false;
        if (wToken.startsWith("-")) {
          isExclude = true;
          wToken = wToken.substring(1);
        }
        const tagTokens = wToken.split("#");
        for (let tagToken of tagTokens) {
          if (!tagToken)
            continue;
          const tag = tagToken.toLowerCase().replace(/[,;]+$/, "");
          if (!tag)
            continue;
          if (isExclude) {
            group.exclude.push(tag);
          } else {
            group.include.push(tag);
          }
        }
      }
      if (group.include.length > 0) {
        query.push(group);
      }
    }
    return query;
  }
};
var TagLogicResolver = class {
  /**
   * Matches a file against a TagQuery.
   */
  static matchesQuery(file, query, metadataCache) {
    if (query.length === 0)
      return false;
    const cache = metadataCache.getFileCache(file);
    if (!cache)
      return false;
    const fileTags = this.getRobustFileTags(cache);
    return query.some((group) => this.matchesGroup(fileTags, group));
  }
  /**
   * More robust version of getAllTags that handles various frontmatter formats.
   */
  static getRobustFileTags(cache) {
    const tags = [...(0, import_obsidian.getAllTags)(cache) || []];
    if (cache.frontmatter) {
      const fmTags = cache.frontmatter.tags || cache.frontmatter.tag;
      if (fmTags) {
        if (Array.isArray(fmTags)) {
          fmTags.forEach((t) => {
            if (typeof t === "string")
              tags.push(t);
          });
        } else if (typeof fmTags === "string") {
          tags.push(...fmTags.split(/[\s,]+/));
        }
      }
    }
    return tags;
  }
  static matchesGroup(fileTags, group) {
    if (group.include.length === 0)
      return false;
    const normalizedFileTags = fileTags.map((t) => (t.startsWith("#") ? t.substring(1) : t).toLowerCase());
    const allIncluded = group.include.every(
      (qTag) => normalizedFileTags.some((fTag) => fTag === qTag || fTag.startsWith(`${qTag}/`))
    );
    if (!allIncluded)
      return false;
    const anyExcluded = group.exclude.some(
      (qTag) => normalizedFileTags.some((fTag) => fTag === qTag || fTag.startsWith(`${qTag}/`))
    );
    return !anyExcluded;
  }
};

// src/CanvasExploder.ts
var HEADING_LIMIT = 10;
var COMPACT_HEIGHT = 50;
var LEAF_HEIGHT = 170;
var DEFAULT_WIDTH = 400;
var MAX_HEIGHT = 600;
var GAP_Y = 20;
var GAP_X = 20;
var CanvasExploder = class {
  constructor(plugin) {
    this.plugin = plugin;
  }
  checkAndAddMenu(menu, title) {
    const activeView = this.plugin.app.workspace.getActiveViewOfType(import_obsidian2.ItemView);
    if (activeView && activeView.getViewType() === "canvas") {
      const canvas = activeView.canvas;
      if (canvas) {
        const selection = canvas.selection;
        if (selection.size === 1) {
          const node = selection.values().next().value;
          if (node && node.file) {
            menu.addItem((item) => {
              item.setTitle(title).onClick(() => {
                this.explodeFileNode(canvas, node);
              });
            });
          } else if (node && node.text !== void 0) {
            menu.addItem((item) => {
              item.setTitle(title).onClick(() => {
                this.explodeTextNode(canvas, node);
              });
            });
          }
        }
      }
    }
  }
  /**
   * Adds the "Split Card by Headings" menu item for text nodes.
   * Called from main.ts when a text node context menu is shown.
   */
  addTextNodeMenu(menu, node) {
    const activeView = this.plugin.app.workspace.getActiveViewOfType(import_obsidian2.ItemView);
    if (!activeView || activeView.getViewType() !== "canvas")
      return;
    const canvas = activeView.canvas;
    if (!canvas)
      return;
    menu.addItem((item) => {
      item.setTitle("Split by Headings").onClick(() => {
        this.explodeTextNode(canvas, node);
      });
    });
  }
  sanitizeHeading(rawHeading) {
    let text = rawHeading.replace(/\[\[|\]\]/g, "");
    text = text.replace(/[\[\](){}<>|#:]/g, " ");
    text = text.replace(/\s+/g, " ");
    return text.trim();
  }
  /**
   * Parses raw markdown text into structured sections based on headings.
   */
  parseMarkdownHeadings(rawText) {
    const lines = rawText.split(/\r?\n/);
    const sections = [];
    let currentSection = null;
    const headingRegex = /^(#{1,6})\s+(.*)/;
    for (const line of lines) {
      const match = line.match(headingRegex);
      if (match) {
        if (currentSection) {
          sections.push({
            level: currentSection.level,
            content: currentSection.lines.join("\n")
          });
        }
        currentSection = {
          level: match[1].length,
          // Number of hashes
          lines: [line]
          // Keep the heading in the content
        };
      } else {
        if (currentSection) {
          currentSection.lines.push(line);
        }
      }
    }
    if (currentSection) {
      sections.push({
        level: currentSection.level,
        content: currentSection.lines.join("\n")
      });
    }
    return sections;
  }
  /**
   * Deconstructs a single file node into a hierarchical tree of connected nodes representing its internal headings,
   * replacing the original node to visualize the document's structure directly on the canvas.
   */
  async explodeFileNode(canvas, originalNode) {
    var _a;
    const targetFile = originalNode.file;
    const cache = this.plugin.app.metadataCache.getFileCache(targetFile);
    if (!cache || !cache.headings || cache.headings.length === 0) {
      new import_obsidian2.Notice(`File "${targetFile.basename}" does not contain any headings to explode.`);
      return;
    }
    const headings = cache.headings;
    const isCompactMode = headings.length > HEADING_LIMIT;
    const baseX = originalNode.x;
    let currentY = originalNode.y;
    const width = Math.max((_a = originalNode.width) != null ? _a : 0, DEFAULT_WIDTH);
    const minLevel = Math.min(...headings.map((h) => h.level));
    const nodeStack = [];
    const newNodesData = [];
    const newEdgesData = [];
    let createdCount = 0;
    const originalData = canvas.getData().nodes.find((n) => n.id === originalNode.id) || {};
    for (let i = 0; i < headings.length; i++) {
      const heading = headings[i];
      const nextHeading = headings[i + 1];
      const isParent = nextHeading && nextHeading.level > heading.level;
      let nodeHeight;
      if (isParent) {
        nodeHeight = COMPACT_HEIGHT;
      } else if (isCompactMode) {
        nodeHeight = LEAF_HEIGHT;
      } else {
        nodeHeight = typeof originalNode.height === "number" && originalNode.height > COMPACT_HEIGHT ? Math.min(MAX_HEIGHT, originalNode.height) : COMPACT_HEIGHT;
      }
      const levelOffset = heading.level - minLevel;
      const currentX = baseX + levelOffset * (width + GAP_X);
      const cleanText = this.sanitizeHeading(heading.heading);
      const subpath = `#${cleanText}`;
      const newNodeId = randomId();
      newNodesData.push({
        ...originalData,
        id: newNodeId,
        type: "file",
        file: targetFile.path,
        subpath,
        x: currentX,
        y: currentY,
        width,
        height: nodeHeight
      });
      createdCount++;
      while (nodeStack.length > 0) {
        const lastEntry = nodeStack[nodeStack.length - 1];
        if (lastEntry.level >= heading.level) {
          nodeStack.pop();
        } else {
          break;
        }
      }
      if (nodeStack.length > 0) {
        const parentEntry = nodeStack[nodeStack.length - 1];
        newEdgesData.push({
          id: randomId(),
          fromNode: parentEntry.nodeId,
          fromSide: "bottom",
          toNode: newNodeId,
          toSide: "left"
        });
      }
      nodeStack.push({
        level: heading.level,
        nodeId: newNodeId
      });
      currentY += nodeHeight + GAP_Y;
    }
    if (createdCount > 0) {
      const currentData = canvas.getData();
      currentData.nodes = currentData.nodes.filter((n) => n.id !== originalNode.id);
      currentData.edges = currentData.edges.filter(
        (e) => e.fromNode !== originalNode.id && e.toNode !== originalNode.id
      );
      currentData.nodes.push(...newNodesData);
      currentData.edges.push(...newEdgesData);
      canvas.setData(currentData);
      canvas.requestSave(false);
      const newNodeIds = new Set(newNodesData.map((n) => n.id));
      canvas.deselectAll();
      for (const [id, node] of canvas.nodes) {
        if (newNodeIds.has(id)) {
          canvas.select(node);
        }
      }
      canvas.zoomToSelection();
    }
    new import_obsidian2.Notice(`Explosion complete, created ${createdCount} nodes.`);
  }
  /**
   * Deconstructs a single text node into a hierarchical tree of connected nodes representing its internal headings,
   * replacing the original node to visualize the card's structure directly on the canvas.
   */
  async explodeTextNode(canvas, originalNode) {
    var _a;
    const rawText = originalNode.text;
    const sections = this.parseMarkdownHeadings(rawText);
    if (sections.length === 0) {
      new import_obsidian2.Notice("No headings found to split.");
      return;
    }
    const baseX = originalNode.x;
    const baseY = originalNode.y;
    const originalWidth = (_a = originalNode.width) != null ? _a : 0;
    const originalHeight = originalNode.height;
    const originalNodeId = originalNode.id;
    const width = Math.max(originalWidth, DEFAULT_WIDTH);
    const minLevel = Math.min(...sections.map((s) => s.level));
    const originalData = canvas.getData().nodes.find((n) => n.id === originalNodeId) || {};
    let currentY = baseY;
    const nodeStack = [];
    const newNodesData = [];
    const newEdgesData = [];
    for (let i = 0; i < sections.length; i++) {
      const section = sections[i];
      const nextSection = sections[i + 1];
      const isParent = nextSection && nextSection.level > section.level;
      const isCompactMode = sections.length > HEADING_LIMIT;
      let nodeHeight;
      if (isParent) {
        nodeHeight = COMPACT_HEIGHT;
      } else if (isCompactMode) {
        nodeHeight = LEAF_HEIGHT;
      } else {
        nodeHeight = typeof originalHeight === "number" && originalHeight > COMPACT_HEIGHT ? Math.min(MAX_HEIGHT, originalHeight) : LEAF_HEIGHT;
      }
      const levelOffset = section.level - minLevel;
      const currentX = baseX + levelOffset * (width + GAP_X);
      const newNodeId = randomId();
      newNodesData.push({
        ...originalData,
        id: newNodeId,
        type: "text",
        text: section.content,
        x: currentX,
        y: currentY,
        width,
        height: nodeHeight
      });
      while (nodeStack.length > 0) {
        const lastEntry = nodeStack[nodeStack.length - 1];
        if (lastEntry.level >= section.level) {
          nodeStack.pop();
        } else {
          break;
        }
      }
      if (nodeStack.length > 0) {
        const parentEntry = nodeStack[nodeStack.length - 1];
        newEdgesData.push({
          id: randomId(),
          fromNode: parentEntry.nodeId,
          fromSide: "bottom",
          toNode: newNodeId,
          toSide: "left"
        });
      }
      nodeStack.push({
        level: section.level,
        nodeId: newNodeId
      });
      currentY += nodeHeight + GAP_Y;
    }
    const currentData = canvas.getData();
    currentData.nodes = currentData.nodes.filter((n) => n.id !== originalNodeId);
    currentData.edges = currentData.edges.filter(
      (e) => e.fromNode !== originalNodeId && e.toNode !== originalNodeId
    );
    currentData.nodes.push(...newNodesData);
    currentData.edges.push(...newEdgesData);
    canvas.setData(currentData);
    canvas.requestSave(false);
    const newNodeIds = new Set(newNodesData.map((n) => n.id));
    canvas.deselectAll();
    for (const [id, node] of canvas.nodes) {
      if (newNodeIds.has(id)) {
        canvas.select(node);
      }
    }
    canvas.zoomToSelection();
    new import_obsidian2.Notice(`Split complete, created ${sections.length} cards.`);
  }
};

// src/SendToCanvas.ts
var import_obsidian3 = require("obsidian");
var SendToCanvas = class {
  constructor(plugin) {
    this.selectedCanvas = null;
    this.statusBarItemEl = null;
    this.plugin = plugin;
  }
  handleSendToCanvas() {
    const currentFile = this.getCurrentMarkdownFile();
    if (!currentFile) {
      new import_obsidian3.Notice("Please open a Markdown file to send to the Canvas.");
      return;
    }
    this.promptCanvasSelectionAndInsert(currentFile);
  }
  handleSendToSelectedCanvas() {
    const currentFile = this.getCurrentMarkdownFile();
    if (!currentFile) {
      new import_obsidian3.Notice("Please open a Markdown file to send to the Canvas.");
      return;
    }
    if (this.selectedCanvas) {
      this.addFileNodeToCanvas(currentFile, this.selectedCanvas);
      new import_obsidian3.Notice(`Using previously selected Canvas: ${this.selectedCanvas.name}`);
    } else {
      new import_obsidian3.Notice(`Failed to send. No Canvas file selected yet.`);
      this.promptCanvasSelectionAndInsert(currentFile);
    }
  }
  getCurrentMarkdownFile() {
    const view = this.plugin.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
    if (!(view == null ? void 0 : view.file) || view.file.extension !== "md")
      return null;
    return view.file;
  }
  promptCanvasSelectionAndInsert(targetFile) {
    const canvasFiles = this.getCanvasFiles();
    if (!canvasFiles.length) {
      new import_obsidian3.Notice("No Canvas files found in vault.");
      return;
    }
    const modal = new CanvasFileSuggestModal(
      this.plugin.app,
      canvasFiles,
      (canvasFile) => {
        this.selectedCanvas = canvasFile;
        this.updateStatusBar();
        this.addFileNodeToCanvas(targetFile, canvasFile);
      }
    );
    modal.open();
  }
  /**
   * Incorporates a file into a Canvas board as a visual node and establishes a bidirectional reference between the document and the workspace.
   *
   * @param targetFile - The file to be added to the visualization.
   * @param canvasFile - The target Canvas file.
   */
  async addFileNodeToCanvas(targetFile, canvasFile) {
    if (!canvasFile || !canvasFile.name)
      return;
    let canvasData;
    const canvasLeaves = this.plugin.app.workspace.getLeavesOfType("canvas");
    const openLeaf = canvasLeaves.find((leaf) => {
      var _a;
      return ((_a = leaf.view.file) == null ? void 0 : _a.path) === canvasFile.path;
    });
    const canvasView = openLeaf ? openLeaf.view : null;
    if (canvasView && canvasView.canvas) {
      canvasData = canvasView.canvas.getData();
    } else {
      const canvasContent = await this.plugin.app.vault.read(canvasFile);
      try {
        canvasData = JSON.parse(canvasContent || '{"nodes":[], "edges":[]}');
      } catch (e) {
        new import_obsidian3.Notice(`Error reading Canvas JSON for ${canvasFile.name}.`);
        console.error("Canvas JSON Parse Error:", e);
        return;
      }
    }
    if (!Array.isArray(canvasData.nodes))
      canvasData.nodes = [];
    if (!Array.isArray(canvasData.edges))
      canvasData.edges = [];
    const existingNode = canvasData.nodes.find((node) => node.type === "file" && node.file === targetFile.path);
    if (existingNode) {
      new import_obsidian3.Notice(`${targetFile.basename} already exists in Canvas.`);
      return;
    }
    const newNode = this.createNodeAtBottom(targetFile, canvasData.nodes);
    canvasData.nodes.push(newNode);
    try {
      if (canvasView && canvasView.canvas) {
        canvasView.canvas.setData(canvasData);
        canvasView.canvas.requestSave();
      } else {
        const updatedContent = JSON.stringify(canvasData, null, 2);
        await this.plugin.app.vault.modify(canvasFile, updatedContent);
      }
      const internalLink = `[[${canvasFile.name}]]`;
      await this.plugin.updateFrontmatter(targetFile, internalLink, "add", "canvas");
      new import_obsidian3.Notice(`Added ${targetFile.basename} to Canvas: ${canvasFile.basename}`);
    } catch (e) {
      new import_obsidian3.Notice(`Failed to add to Canvas: ${canvasFile.name}`);
      console.error("Canvas Modify Error:", e);
    }
  }
  /**
   * Creates a new node for a file at the bottom of the canvas.
   *
   * @param file - The file to create a node for.
   * @param existingNodes - The existing nodes in the canvas.
   * @returns The new node.
   */
  createNodeAtBottom(file, existingNodes) {
    const id = randomId();
    const WIDTH = this.plugin.settings.defaultFileNodeWidth;
    const HEIGHT = this.plugin.settings.defaultFileNodeHeight;
    const GAP = 100;
    const DEFAULT_X = -200;
    let startY = -200;
    if (existingNodes.length > 0) {
      const maxY = existingNodes.reduce((max, node) => {
        const bottomEdge = node.y + node.height;
        return bottomEdge > max ? bottomEdge : max;
      }, -Infinity);
      if (maxY !== -Infinity) {
        startY = maxY + GAP;
      }
    }
    return {
      id,
      x: DEFAULT_X,
      y: startY,
      width: WIDTH,
      height: HEIGHT,
      type: "file",
      file: file.path
    };
  }
  getCanvasFiles() {
    return this.plugin.app.vault.getFiles().filter((file) => file.extension === "canvas");
  }
  updateStatusBar() {
    const file = this.selectedCanvas;
    if (file) {
      if (!this.statusBarItemEl) {
        this.statusBarItemEl = this.plugin.addStatusBarItem();
        this.statusBarItemEl.addClass("scs-status-canvas");
        this.plugin.registerDomEvent(this.statusBarItemEl, "click", this.handleStatusBarClick.bind(this));
      }
      this.statusBarItemEl.empty();
      this.statusBarItemEl.setText(`Selected Canvas: ${file.name}`);
      this.statusBarItemEl.title = `Click to clear selection: ${file.name}`;
      this.statusBarItemEl.addClass("is-active");
    } else {
      this.clearStatusBar();
    }
  }
  handleStatusBarClick(evt) {
    evt.preventDefault();
    this.clearSelectedCanvas();
  }
  clearSelectedCanvas(showNotice = true) {
    if (this.selectedCanvas) {
      const fileName = this.selectedCanvas.name;
      this.selectedCanvas = null;
      this.clearStatusBar();
      if (showNotice) {
        new import_obsidian3.Notice(`Cleared selected Canvas: ${fileName}`);
      }
    } else if (showNotice) {
      new import_obsidian3.Notice("No Canvas file is currently selected.");
    }
  }
  clearStatusBar() {
    if (this.statusBarItemEl) {
      this.statusBarItemEl.remove();
      this.statusBarItemEl = null;
    }
  }
};
var CanvasFileSuggestModal = class extends import_obsidian3.FuzzySuggestModal {
  constructor(app, files, onSelect) {
    super(app);
    this.files = files;
    this.onSelect = onSelect;
    this.setPlaceholder("Select a Canvas file...");
  }
  getItems() {
    return this.files;
  }
  getItemText(file) {
    return file.path;
  }
  onChooseItem(file, evt) {
    this.onSelect(file);
    this.close();
  }
};

// src/AdvancedTagSuggestModal.ts
var import_obsidian4 = require("obsidian");
var NODE_GAP = 20;
var AdvancedTagSuggestModal = class extends import_obsidian4.Modal {
  constructor(app, plugin, canvas, position) {
    super(app);
    this.suggestions = [];
    this.selectedIndex = -1;
    this.allTags = [];
    this.plugin = plugin;
    this.canvas = canvas;
    this.position = position;
    this.allTags = this.getTags();
  }
  onOpen() {
    const { contentEl, titleEl } = this;
    titleEl.setText("Add notes by tag (Advanced)");
    contentEl.createEl("p", {
      text: "Use space for AND, 'OR' for OR, and '-' for NOT. Example: #tag1 #tag2 -#tag3",
      cls: "setting-item-description"
    });
    const inputContainer = contentEl.createDiv({ cls: "advanced-tag-input-container" });
    this.inputComponent = new import_obsidian4.TextComponent(inputContainer);
    this.inputComponent.setPlaceholder("Enter tag query...");
    this.inputComponent.onChange(() => {
      this.updateSuggestions();
    });
    this.inputComponent.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "ArrowDown") {
        e.preventDefault();
        this.navigateSuggestions(1);
      } else if (e.key === "ArrowUp") {
        e.preventDefault();
        this.navigateSuggestions(-1);
      } else if (e.key === "Enter") {
        if (this.selectedIndex !== -1 && this.suggestions.length > 0) {
          e.preventDefault();
          this.selectSuggestion(this.suggestions[this.selectedIndex]);
        } else {
          this.executeImport();
        }
      } else if (e.key === "Escape") {
        if (this.suggestions.length > 0) {
          e.preventDefault();
          this.clearSuggestions();
        }
      }
    });
    new import_obsidian4.ButtonComponent(inputContainer).setButtonText("Import").setCta().onClick(() => {
      this.executeImport();
    });
    this.suggestionContainer = contentEl.createDiv({ cls: "advanced-tag-suggestions" });
    this.inputComponent.inputEl.focus();
  }
  /**
   * Retrieves all tags from the metadata cache.
   * Note: getTags() can be stale-on-open if the cache hasn't updated recently,
   * but it's the most efficient way to get a list of all existing tags.
   */
  getTags() {
    const tagsMap = this.app.metadataCache.getTags();
    const tags = /* @__PURE__ */ new Set();
    for (const tag of Object.keys(tagsMap)) {
      tags.add(tag);
      this.addParentTags(tag, tags);
    }
    return Array.from(tags).sort((a, b) => a.localeCompare(b));
  }
  addParentTags(tag, tags) {
    const parts = tag.split("/");
    if (parts.length <= 1)
      return;
    for (let depth = 1; depth < parts.length; depth++) {
      tags.add(parts.slice(0, depth).join("/"));
    }
  }
  updateSuggestions() {
    const value = this.inputComponent.getValue();
    const cursorPosition = this.inputComponent.inputEl.selectionStart || 0;
    const beforeCursor = value.substring(0, cursorPosition);
    const lastWordMatch = beforeCursor.match(/([-#]?)[^\s#|]*$/);
    if (!lastWordMatch || lastWordMatch[0].length === 0) {
      this.clearSuggestions();
      return;
    }
    const lastWord = lastWordMatch[0];
    let query = lastWord;
    if (query.startsWith("-"))
      query = query.substring(1);
    if (query.startsWith("#"))
      query = query.substring(1);
    if (query.length === 0) {
      this.clearSuggestions();
      return;
    }
    this.suggestions = this.allTags.filter((tag) => tag.toLowerCase().includes(query.toLowerCase())).slice(0, 10);
    this.renderSuggestions();
  }
  renderSuggestions() {
    this.suggestionContainer.empty();
    this.selectedIndex = -1;
    if (this.suggestions.length === 0) {
      this.suggestionContainer.removeClass("is-visible");
      return;
    }
    this.suggestionContainer.addClass("is-visible");
    this.suggestions.forEach((suggestion, index) => {
      const div = this.suggestionContainer.createDiv({
        text: suggestion,
        cls: "suggestion-item"
      });
      div.addEventListener("click", () => {
        this.selectSuggestion(suggestion);
      });
      div.addEventListener("mouseenter", () => {
        this.setHighlight(index);
      });
    });
    this.setHighlight(0);
  }
  setHighlight(index) {
    const items = this.suggestionContainer.querySelectorAll(".suggestion-item");
    items.forEach((item, i) => {
      if (i === index) {
        item.addClass("is-selected");
      } else {
        item.removeClass("is-selected");
      }
    });
    this.selectedIndex = index;
  }
  navigateSuggestions(direction) {
    if (this.suggestions.length === 0)
      return;
    let newIndex = this.selectedIndex + direction;
    if (newIndex < 0)
      newIndex = this.suggestions.length - 1;
    if (newIndex >= this.suggestions.length)
      newIndex = 0;
    this.setHighlight(newIndex);
    const highlightedItem = this.suggestionContainer.querySelectorAll(".suggestion-item")[newIndex];
    if (highlightedItem) {
      highlightedItem.scrollIntoView({ block: "nearest" });
    }
  }
  selectSuggestion(suggestion) {
    const value = this.inputComponent.getValue();
    const cursorPosition = this.inputComponent.inputEl.selectionStart || 0;
    const beforeCursor = value.substring(0, cursorPosition);
    const afterCursor = value.substring(cursorPosition);
    const lastWordMatch = beforeCursor.match(/([-#]?)[^\s#|]*$/);
    if (lastWordMatch) {
      const prefix = lastWordMatch[1];
      const startOfWord = cursorPosition - lastWordMatch[0].length;
      let newPrefix = prefix;
      if (!newPrefix) {
        newPrefix = "#";
      } else if (newPrefix === "-") {
        newPrefix = "-#";
      }
      let cleanSuggestion = suggestion;
      if (cleanSuggestion.startsWith("#")) {
        cleanSuggestion = cleanSuggestion.substring(1);
      }
      const newValue = value.substring(0, startOfWord) + newPrefix + cleanSuggestion + afterCursor;
      this.inputComponent.setValue(newValue);
      this.inputComponent.inputEl.focus();
      const newCursorPos = startOfWord + newPrefix.length + cleanSuggestion.length;
      this.inputComponent.inputEl.setSelectionRange(newCursorPos, newCursorPos);
    }
    this.clearSuggestions();
  }
  clearSuggestions() {
    this.suggestionContainer.empty();
    this.suggestionContainer.removeClass("is-visible");
    this.suggestions = [];
    this.selectedIndex = -1;
  }
  executeImport() {
    const queryStr = this.inputComponent.getValue();
    if (!queryStr.trim())
      return;
    const query = TagQueryParser.parse(queryStr);
    if (query.length === 0) {
      new import_obsidian4.Notice("Invalid query. Ensure you have at least one inclusion tag (e.g., #tag).");
      return;
    }
    const matchingFiles = this.app.vault.getMarkdownFiles().filter((file) => TagLogicResolver.matchesQuery(file, query, this.app.metadataCache)).sort((a, b) => a.path.localeCompare(b.path));
    if (matchingFiles.length === 0) {
      new import_obsidian4.Notice(`No files found matching the query: ${queryStr}`);
      return;
    }
    this.addFilesToCanvas(matchingFiles);
    this.close();
  }
  addFilesToCanvas(files) {
    const width = this.plugin.settings.defaultFileNodeWidth;
    const height = this.plugin.settings.defaultFileNodeHeight;
    const columns = Math.ceil(Math.sqrt(files.length));
    const createdNodes = [];
    files.forEach((file, index) => {
      const x = this.position.x + index % columns * (width + NODE_GAP);
      const y = this.position.y + Math.floor(index / columns) * (height + NODE_GAP);
      try {
        const node = this.canvas.createFileNode({
          file,
          pos: { x, y },
          size: { width, height },
          save: false,
          focus: false
        });
        if (node) {
          createdNodes.push(node);
        }
      } catch (error) {
        console.error(`Enhanced Canvas: failed to create Canvas node for ${file.path}`, error);
      }
    });
    if (createdNodes.length === 0) {
      new import_obsidian4.Notice(`Failed to add notes to Canvas.`);
      return;
    }
    this.selectNodes(createdNodes);
    this.canvas.requestSave();
    new import_obsidian4.Notice(`Added ${createdNodes.length} node${createdNodes.length === 1 ? "" : "s"}.`);
  }
  selectNodes(nodes) {
    this.canvas.deselectAll();
    for (const node of nodes) {
      this.canvas.selection.add(node);
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/CanvasTagImport.ts
var CanvasTagImport = class {
  constructor(plugin) {
    this.patched = false;
    this.menus = /* @__PURE__ */ new WeakSet();
    this.leafEvent = null;
    this.layoutEvent = null;
    this.plugin = plugin;
  }
  register() {
    const tryToPatch = () => {
      if (this.patchCanvasCreationMenu()) {
        this.detachPatchListeners();
      }
    };
    this.leafEvent = this.plugin.app.workspace.on("active-leaf-change", tryToPatch);
    this.layoutEvent = this.plugin.app.workspace.on("layout-change", tryToPatch);
    this.plugin.registerEvent(this.leafEvent);
    this.plugin.registerEvent(this.layoutEvent);
    this.plugin.app.workspace.onLayoutReady(tryToPatch);
    tryToPatch();
  }
  patchCanvasCreationMenu() {
    var _a, _b;
    if (this.patched)
      return true;
    const canvas = this.getAnyCanvas();
    if (!((_b = (_a = canvas == null ? void 0 : canvas.constructor) == null ? void 0 : _a.prototype) == null ? void 0 : _b.showCreationMenu))
      return false;
    const plugin = this.plugin;
    const tagImport = this;
    const uninstall = around(canvas.constructor.prototype, {
      showCreationMenu: (next) => {
        return function(menu, position, ...args) {
          const result = next.call(this, menu, position, ...args);
          tagImport.addMenuItem(menu, this, position);
          return result;
        };
      }
    });
    plugin.register(uninstall);
    this.patched = true;
    return true;
  }
  detachPatchListeners() {
    if (this.leafEvent) {
      this.plugin.app.workspace.offref(this.leafEvent);
      this.leafEvent = null;
    }
    if (this.layoutEvent) {
      this.plugin.app.workspace.offref(this.layoutEvent);
      this.layoutEvent = null;
    }
  }
  getAnyCanvas() {
    var _a, _b;
    const canvasView = (_b = (_a = this.plugin.app.workspace.getLeavesOfType("canvas")) == null ? void 0 : _a[0]) == null ? void 0 : _b.view;
    if (!canvasView || canvasView.getViewType() !== "canvas")
      return null;
    return canvasView.canvas;
  }
  addMenuItem(menu, canvas, position) {
    if (!canvas || canvas.readonly || this.menus.has(menu))
      return;
    this.menus.add(menu);
    menu.addItem((item) => {
      item.setTitle("Add notes by tag...").setIcon("hashtag").setSection("create").onClick(() => {
        new AdvancedTagSuggestModal(this.plugin.app, this.plugin, canvas, position).open();
      });
    });
  }
};

// src/settings.ts
var DEFAULT_SETTINGS = {
  showReleaseNotes: true,
  previousRelease: "0.0.0",
  enableFrontmatter: true,
  enableCustomCSS: true,
  defaultTextNodeWidth: 250,
  defaultTextNodeHeight: 60,
  defaultFileNodeWidth: 400,
  defaultFileNodeHeight: 400
};

// src/ReleaseNotesModal.ts
var import_obsidian5 = require("obsidian");

// src/releaseNotesData.ts
var firstInstallContent = `
Building upon the original "Property Link" and "Auto Focus" features, I am excited to share three key additions in recent updates.
### \u2728 Split Node by Headings

**Split Node by Headings** instantly deconstructs a single file node into a hierarchical tree based on its headings. You can try this by right-clicking on a file node and selecting "Split Node by Headings" in Canvas.

### \u2728 Send Note to Canvas

With the **"Send to Canvas"** plugin command, you can push your current markdown note directly to a specific Canvas. It automatically appends a "canvas" property to your note, allowing you to navigate back to the board instantly in the future.

Once you have sent a note, that Canvas becomes the "Selected." You can then use the **"Send to Selected Canvas"** plugin command on other notes to instantly add them to the same board\u2014bypassing the file selection step entirely.

### \u2728 Auto-Resize Node

This is a feature I\u2019ve wanted for a long time. Previously, double-clicking the bottom edge would fit a node to its content, but changing the width would break this fit, forcing you to double-click again.

With this update, double-clicking the bottom edge activates "Auto-Resize." Now, the node's height dynamically adapts to fit your content\u2014whether you are **adjusting the width** or **updating the text**. No need for repeated double-clicking!

[View detailed demo at github](https://github.com/RobertttBS/obsidian-enhanced-canvas)
`;
var fixCursorShiftIssueInStackTabsCanvas = `
> [!tip] Feature in 1.0.24
> Implement configurable default dimensions for new canvas nodes. Check the Enhanced Canvas settings to configure your preferred width and height.

> [!note] Feature in 1.0.23
> Added "Add notes by tag..." right-click menu option to bulk import notes by tag.

> [!bug] Fixed in 1.0.22
> Fixed an issue where properties failed to sync for pinned Canvas tabs on Windows 11. (I hope the bug is gone.)

> [!note] Feature in 1.0.21
> Since the Obsidian Canvas core plugin now supports backlinks, I have added a settings view to Enhanced Canvas that allows you to toggle the "Sync Frontmatter" feature (as well as the plugin's CSS). If you prefer not to have this property added, you can simply disable the "Sync Frontmatter" feature.

> [!tip] Feature in 1.0.20
> Added "Focus" functionality for Linked Mentions.

> [!NOTE] Feature in 1.0.19
> Added "Split by Headings" functionality for Card Nodes.

> [!bug] Fixed in 1.0.18
> You can now use Canvas with "stacked tabs" enabled without experiencing the cursor position shift issue.
> This fix applies to the Obsidian Canvas core plugin rather than this specific plugin.
`;
var releaseNotesContent = {
  "1.0.24": fixCursorShiftIssueInStackTabsCanvas,
  "1.0.23": fixCursorShiftIssueInStackTabsCanvas,
  "1.0.22": fixCursorShiftIssueInStackTabsCanvas,
  "1.0.21": fixCursorShiftIssueInStackTabsCanvas,
  "1.0.20": fixCursorShiftIssueInStackTabsCanvas,
  "1.0.19": fixCursorShiftIssueInStackTabsCanvas,
  "1.0.18": fixCursorShiftIssueInStackTabsCanvas,
  "1.0.17": firstInstallContent
};

// src/ReleaseNotesModal.ts
var ReleaseNotesModal = class extends import_obsidian5.Modal {
  constructor(app, plugin, version, isNewInstall, previousVersion = "0.0.0") {
    super(app);
    this.plugin = plugin;
    this.version = version;
    this.isNewInstall = isNewInstall;
    this.previousVersion = previousVersion;
  }
  onOpen() {
    const { contentEl, titleEl } = this;
    titleEl.setText(
      this.isNewInstall ? "Welcome to Enhanced Canvas" : `Enhanced Canvas updated to v${this.version}`
    );
    contentEl.classList.add("enhanced-canvas-release-notes");
    this.renderContent();
  }
  async renderContent() {
    const { contentEl } = this;
    let markdownText = "";
    if (this.isNewInstall) {
      markdownText = firstInstallContent;
    } else {
      const notes = [];
      const versions = Object.keys(releaseNotesContent).sort((a, b) => isVersionNewer(a, b) ? -1 : 1);
      for (const v of versions) {
        if (isVersionNewer(v, this.previousVersion) && !isVersionNewer(v, this.version)) {
          notes.push(releaseNotesContent[v]);
        }
      }
      markdownText = notes.length > 0 ? notes.join("\n\n---\n\n") : "Thank you for updating! This update includes bug fixes.";
    }
    await import_obsidian5.MarkdownRenderer.render(
      this.app,
      markdownText,
      contentEl,
      "/",
      this.plugin
    );
    const buttonContainer = contentEl.createDiv({ cls: "release-notes-button-container" });
    buttonContainer.style.marginTop = "20px";
    buttonContainer.style.textAlign = "right";
    new import_obsidian5.ButtonComponent(buttonContainer).setButtonText("Got it").setCta().onClick(() => {
      this.close();
    });
  }
  async onClose() {
    this.contentEl.empty();
    if (this.plugin.settings.previousRelease !== this.version) {
      this.plugin.settings.previousRelease = this.version;
      await this.plugin.saveSettings();
    }
  }
};

// main.ts
var EnhancedCanvas = class extends import_obsidian6.Plugin {
  constructor() {
    super(...arguments);
    this.isMetadataClicked = false;
    this.autoHeightCheckReference = null;
    this.autoLinkCheckReference = null;
    this.dragTempNodeCheckReference = null;
    this.canvasStackInterval = null;
    this.autoHeightUninstaller = null;
    this.dragTempNodeUninstaller = null;
    /**
     * Modifies a file's frontmatter property to ensure a specific value is either 
     * included or excluded while maintaining list integrity.
     */
    this.updateFrontmatter = async (file, link, action, propertyName) => {
      if (!this.settings.enableFrontmatter)
        return;
      await this.app.fileManager.processFrontMatter(file, (fm) => {
        const existingValue = Reflect.get(fm, propertyName);
        let currentSet = /* @__PURE__ */ new Set();
        let wasString = false;
        if (Array.isArray(existingValue)) {
          existingValue.filter((item) => typeof item === "string" && item.trim() !== "").forEach((item) => currentSet.add(item));
        } else if (typeof existingValue === "string" && existingValue.trim() !== "") {
          currentSet.add(existingValue);
          wasString = true;
        }
        if (action === "add") {
          currentSet.add(link);
        } else if (action === "remove") {
          currentSet.delete(link);
        }
        const finalArray = Array.from(currentSet);
        if (finalArray.length > 0) {
          if (finalArray.length === 1 && wasString) {
            Reflect.set(fm, propertyName, finalArray[0]);
          } else {
            Reflect.set(fm, propertyName, finalArray);
          }
        } else {
          Reflect.deleteProperty(fm, propertyName);
        }
      });
    };
    this.ifActiveViewIsCanvas = (commandFn) => (checking) => {
      const activeView = this.app.workspace.getActiveViewOfType(import_obsidian6.ItemView);
      if ((activeView == null ? void 0 : activeView.getViewType()) !== "canvas") {
        return checking ? false : void 0;
      }
      if (checking)
        return true;
      const canvas = activeView.canvas;
      const canvasData = canvas == null ? void 0 : canvas.getData();
      if (!canvas || !canvasData)
        return;
      return commandFn(canvas, canvasData);
    };
  }
  /**
   * Scans the selected nodes to identify underlying file references and automatically
   * generates visual connections where valid links exist between files but edges are
   * currently missing on the canvas.
   */
  createMissingEdgesFromLinks(canvas) {
    const selectedNodes = Array.from(canvas.selection);
    const fileNodes = selectedNodes.filter((node) => !!(node == null ? void 0 : node.filePath));
    const resolvedLinks = this.app.metadataCache.resolvedLinks;
    const currentData = canvas.getData();
    const existingEdgesMap = /* @__PURE__ */ new Map();
    currentData.edges.forEach((edge) => {
      existingEdgesMap.set(`${edge.fromNode}->${edge.toNode}`, edge);
    });
    const filePathToNodeMap = /* @__PURE__ */ new Map();
    fileNodes.forEach((node) => {
      if (node.filePath) {
        filePathToNodeMap.set(node.filePath, node);
      }
    });
    const newEdges = [];
    fileNodes.forEach((sourceNode) => {
      if (!sourceNode.filePath)
        return;
      const links = resolvedLinks[sourceNode.filePath];
      if (!links)
        return;
      Object.keys(links).forEach((targetPath) => {
        const targetNode = filePathToNodeMap.get(targetPath);
        if (targetNode && targetNode !== sourceNode) {
          const edgeKey = `${sourceNode.id}->${targetNode.id}`;
          if (!existingEdgesMap.has(edgeKey)) {
            const newEdge = this.createEdge(sourceNode, targetNode);
            newEdges.push(newEdge);
            existingEdgesMap.set(edgeKey, newEdge);
          }
        }
      });
    });
    if (newEdges.length > 0) {
      currentData.edges.push(...newEdges);
      canvas.setData(currentData);
      canvas.requestSave(false);
    }
  }
  /**
   * Recomputes the connection anchor points for all edges contained within the
   * current selection to ensure optimal visual alignment and routing.
   */
  optimizeEdgesBetweenSelectedNodes(canvas) {
    const selectedNodes = Array.from(canvas.selection);
    if (selectedNodes.length < 2)
      return;
    const currentData = canvas.getData();
    const selectedNodeIds = new Set(selectedNodes.map((node) => node.id));
    let didUpdateEdges = false;
    currentData.edges.forEach((edge) => {
      if (selectedNodeIds.has(edge.fromNode) && selectedNodeIds.has(edge.toNode)) {
        const fromNode = currentData.nodes.find((node) => node.id === edge.fromNode);
        const toNode = currentData.nodes.find((node) => node.id === edge.toNode);
        if (fromNode && toNode) {
          const updatedEdge = this.createEdge(fromNode, toNode);
          if (edge.fromSide !== updatedEdge.fromSide || edge.toSide !== updatedEdge.toSide) {
            edge.fromSide = updatedEdge.fromSide;
            edge.toSide = updatedEdge.toSide;
            didUpdateEdges = true;
          }
        }
      }
    });
    if (didUpdateEdges) {
      canvas.setData(currentData);
      canvas.requestSave(false);
    }
  }
  deleteEdges(canvas) {
    const selectedNodes = Array.from(canvas.selection);
    const selectedNodeIds = new Set(selectedNodes.map((node) => node.id));
    const currentData = canvas.getData();
    currentData.edges = currentData.edges.filter((edge) => {
      return !(selectedNodeIds.has(edge.fromNode) && selectedNodeIds.has(edge.toNode));
    });
    canvas.setData(currentData);
    canvas.requestSave(false);
  }
  /**
   * add 'canvas' and canvas basename properties to the node frontmatter.
   */
  addProperty(node, propertyName, basename) {
    if (!this.settings.enableFrontmatter)
      return;
    const file = this.app.vault.getFileByPath(node.file);
    if (!file)
      return;
    this.app.fileManager.processFrontMatter(file, (frontmatter) => {
      if (!frontmatter)
        return;
      if (!frontmatter.canvas) {
        frontmatter.canvas = [];
      }
      const canvasLink = `[[${propertyName}]]`;
      if (!frontmatter.canvas.includes(canvasLink)) {
        frontmatter.canvas.push(canvasLink);
      }
      if (!frontmatter[basename]) {
        frontmatter[basename] = [];
      }
    });
  }
  /**
   * For JSON nodes only, which are stored in the canvas file, not the canvas node in Obsidian.
   */
  removeProperty(node, propertyName, basename) {
    if (!this.settings.enableFrontmatter)
      return;
    const file = this.app.vault.getFileByPath(node.file);
    if (!file)
      return;
    return this.app.fileManager.processFrontMatter(file, (frontmatter) => {
      if (!frontmatter)
        return;
      if (frontmatter[basename]) {
        delete frontmatter[basename];
      }
      if (frontmatter.canvas) {
        const canvasLink = `[[${propertyName}]]`;
        frontmatter.canvas = frontmatter.canvas.filter((link) => link !== canvasLink);
        if (frontmatter.canvas.length === 0) {
          delete frontmatter.canvas;
        }
      }
    });
  }
  /**
   * For JSON nodes only, which are stored in the canvas file, not the canvas node in Obsidian.
   */
  renameProperty(node, oldName, newName) {
    if (!this.settings.enableFrontmatter)
      return;
    const file = this.app.vault.getFileByPath(node.file);
    if (!file)
      return;
    const getBaseName = (name) => name.substring(name.lastIndexOf("/") + 1);
    newName = getBaseName(newName);
    const oldBaseName = oldName.endsWith(".canvas") ? oldName.slice(0, -7) : oldName;
    const newBaseName = newName.endsWith(".canvas") ? newName.slice(0, -7) : newName;
    this.app.fileManager.processFrontMatter(file, (frontmatter) => {
      if (!frontmatter)
        return;
      const newFrontmatter = Object.fromEntries(
        Object.entries(frontmatter).map(([key, value]) => [
          key === oldBaseName ? newBaseName : key,
          value
        ])
      );
      Object.keys(frontmatter).forEach((key) => {
        delete frontmatter[key];
      });
      Object.assign(frontmatter, newFrontmatter);
    });
  }
  async removeAllProperty(canvas, canvasData) {
    if (!this.settings.enableFrontmatter)
      return;
    const nodes = canvasData.nodes;
    await Promise.all(nodes.map((node) => {
      if (!(node == null ? void 0 : node.file))
        return;
      return this.removeProperty(node, canvas.view.file.name, canvas.view.file.basename);
    }));
    canvas.setData(canvasData);
    canvas.requestSave(false);
  }
  async processEdgeUpdate(e) {
    var _a, _b;
    if (!this.settings.enableFrontmatter)
      return;
    const fromNode = (_a = e == null ? void 0 : e.from) == null ? void 0 : _a.node;
    const toNode = (_b = e == null ? void 0 : e.to) == null ? void 0 : _b.node;
    if (!fromNode || !toNode)
      return;
    if (!(fromNode == null ? void 0 : fromNode.filePath) && !(fromNode == null ? void 0 : fromNode.file))
      return;
    const fromFilePath = fromNode.filePath || fromNode.file;
    const toFilePath = toNode.filePath || toNode.file;
    const fromFile = this.app.vault.getFileByPath(fromFilePath);
    const toFile = this.app.vault.getFileByPath(toFilePath);
    if (fromFilePath === toFilePath)
      return;
    if (!fromFile || !toFile)
      return;
    const canvasName = e.canvas.view.file.basename;
    let link = this.app.fileManager.generateMarkdownLink(toFile, fromFilePath).replace(/^!(\[\[.*\]\])$/, "$1");
    await this.updateFrontmatter(fromFile, link, "add", canvasName);
  }
  /**
   * Orchestrates a batch update for all connections within the provided canvas data
   * to ensure every edge is validated and processed according to the plugin's
   * current update logic.
   */
  async processEdgesInCanvas(canvasData, canvasFile) {
    if (!canvasData || !this.settings.enableFrontmatter)
      return;
    const nodeIdToNodeMap = /* @__PURE__ */ new Map();
    if (canvasData.nodes && Array.isArray(canvasData.nodes)) {
      for (const node of canvasData.nodes) {
        nodeIdToNodeMap.set(node.id, node);
      }
    }
    const fileLinksToAdd = /* @__PURE__ */ new Map();
    if (canvasData.edges && Array.isArray(canvasData.edges)) {
      for (const edgeData of canvasData.edges) {
        const fromNode = nodeIdToNodeMap.get(edgeData.fromNode);
        const toNode = nodeIdToNodeMap.get(edgeData.toNode);
        if (!fromNode || !toNode)
          continue;
        let fromFilePath = (fromNode == null ? void 0 : fromNode.filePath) ? fromNode.filePath : fromNode.file;
        let toFilePath = (toNode == null ? void 0 : toNode.filePath) ? toNode.filePath : toNode.file;
        if (!fromFilePath || !toFilePath)
          continue;
        const fromFile = this.app.vault.getFileByPath(fromFilePath);
        const toFile = this.app.vault.getFileByPath(toFilePath);
        if (fromFilePath === toFilePath)
          continue;
        if (!fromFile || !toFile)
          continue;
        let link = this.app.fileManager.generateMarkdownLink(toFile, fromFilePath).replace(/^!(\[\[.*\]\])$/, "$1");
        if (!fileLinksToAdd.has(fromFilePath)) {
          fileLinksToAdd.set(fromFilePath, /* @__PURE__ */ new Set());
        }
        fileLinksToAdd.get(fromFilePath).add(link);
      }
    }
    const canvasName = canvasFile.basename;
    for (const [fromFilePath, links] of fileLinksToAdd.entries()) {
      const fromFile = this.app.vault.getFileByPath(fromFilePath);
      if (fromFile) {
        await this.app.fileManager.processFrontMatter(fromFile, (fm) => {
          const existingValue = Reflect.get(fm, canvasName);
          let currentSet = /* @__PURE__ */ new Set();
          let wasString = false;
          if (Array.isArray(existingValue)) {
            existingValue.filter((item) => typeof item === "string" && item.trim() !== "").forEach((item) => currentSet.add(item));
          } else if (typeof existingValue === "string" && existingValue.trim() !== "") {
            currentSet.add(existingValue);
            wasString = true;
          }
          for (const link of links) {
            currentSet.add(link);
          }
          const finalArray = Array.from(currentSet);
          if (finalArray.length > 0) {
            if (finalArray.length === 1 && wasString) {
              Reflect.set(fm, canvasName, finalArray[0]);
            } else {
              Reflect.set(fm, canvasName, finalArray);
            }
          } else {
            Reflect.deleteProperty(fm, canvasName);
          }
        });
      }
    }
  }
  /** Applies or removes the body CSS class that gates the optional visual styles. */
  toggleCSSClass(enabled) {
    if (enabled) {
      document.body.classList.add("enhanced-canvas-enabled");
    } else {
      document.body.classList.remove("enhanced-canvas-enabled");
    }
  }
  /**
   * Registers all core plugin features and performs an initial scan
   * of the vault to process and initialize data from all
   * existing canvas files upon loading.
   */
  async onload() {
    await this.loadSettings();
    this.checkReleaseNotes();
    this.exploder = new CanvasExploder(this);
    this.sendToCanvas = new SendToCanvas(this);
    this.canvasTagImport = new CanvasTagImport(this);
    this.addSettingTab(new EnhancedCanvasSettingTab(this.app, this));
    this.toggleCSSClass(this.settings.enableCustomCSS);
    this.registerPluginCommands();
    this.registerCanvasAutoLink();
    this.registerFileManagerPatches();
    this.registerFocusCanvas();
    this.registerCanvasExploder();
    this.registerCanvasTagImport();
    this.registerCanvasNodeAutoHeightPatcher();
    this.registerCanvasDefaultNodeSize();
    this.registerCanvasDragTempNodePatcher();
    try {
      const canvasFiles = this.app.vault.getFiles().filter((file) => file.extension === "canvas");
      await Promise.all(canvasFiles.map(async (canvasFile) => {
        try {
          const content = await this.app.vault.read(canvasFile);
          if (!content || content.trim() === "")
            return;
          try {
            const canvasData = JSON.parse(content);
            if (!canvasData)
              return;
            if (canvasData.nodes && Array.isArray(canvasData.nodes)) {
              for (const node of canvasData.nodes) {
                if (!(node == null ? void 0 : node.file))
                  continue;
                this.addProperty(node, canvasFile.name, canvasFile.basename);
              }
            }
            await this.processEdgesInCanvas(canvasData, canvasFile);
          } catch (parseError) {
            console.error("Enhanced Canvas: Failed to parse canvas data", parseError);
            return;
          }
        } catch (fileError) {
          console.error("Enhanced Canvas: Failed to read canvas file", fileError);
          return;
        }
      }));
    } catch (error) {
      console.error("Enhanced Canvas: Error in metadata update loop", error);
      return;
    }
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", (leaf) => {
        if (this.canvasStackInterval) {
          clearInterval(this.canvasStackInterval);
          this.canvasStackInterval = null;
        }
        if (!leaf)
          return;
        const isStacked = !!document.querySelector(".workspace-tabs.mod-stacked");
        if (!isStacked)
          return;
        const view = leaf.view;
        if (view.getViewType() !== "canvas")
          return;
        if (typeof view.onResize === "function") {
          view.onResize();
        }
        setTimeout(() => {
          if (typeof view.onResize === "function")
            view.onResize();
        }, 200);
        let lastLeft = view.containerEl.getBoundingClientRect().left;
        this.canvasStackInterval = window.setInterval(() => {
          if (!view || !view.containerEl) {
            if (this.canvasStackInterval !== null) {
              clearInterval(this.canvasStackInterval);
              this.canvasStackInterval = null;
            }
            return;
          }
          const rect = view.containerEl.getBoundingClientRect();
          if (Math.abs(rect.left - lastLeft) > 2) {
            if (typeof view.onResize === "function") {
              view.onResize();
            }
            lastLeft = rect.left;
          }
        }, 200);
        this.registerInterval(this.canvasStackInterval);
      })
    );
  }
  checkReleaseNotes() {
    try {
      const currentVersion = this.manifest.version;
      const previousVersion = this.settings.previousRelease;
      const isNewInstall = previousVersion === "0.0.0" || !previousVersion;
      if (this.settings.showReleaseNotes) {
        if (isNewInstall || isVersionNewer(currentVersion, previousVersion)) {
          new ReleaseNotesModal(
            this.app,
            this,
            currentVersion,
            isNewInstall,
            previousVersion
          ).open();
        }
      }
    } catch (e) {
      console.error("Failed to show release notes:", e);
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /**
   * Registers patches for the application's FileManager to intercept file deletion
   * and rename operations. This function ensures data integrity by automatically
   * cleaning up references to the modified files throughout the vault before the
   * original operation proceeds.
   */
  registerFileManagerPatches() {
    const plugin = this;
    const deleteFile = async (file) => {
      if (file.deleted === true)
        return;
      const backLinks = plugin.app.metadataCache.getBacklinksForFile(file);
      if (!backLinks || !backLinks.data)
        return;
      const linkRegexBasename = new RegExp(`\\[\\[${file.basename}(\\|.*)?\\]\\]`);
      const linkRegexFullName = new RegExp(`\\[\\[${file.name}(\\|.*)?\\]\\]`);
      for (const [sourcePath, references] of backLinks.data.entries()) {
        const sourceFile = plugin.app.vault.getFileByPath(sourcePath);
        if (!sourceFile || sourceFile.extension !== "md")
          continue;
        await plugin.app.fileManager.processFrontMatter(sourceFile, (frontmatter) => {
          if (!frontmatter)
            return;
          Object.keys(frontmatter).forEach((key) => {
            if (Array.isArray(frontmatter[key])) {
              frontmatter[key] = frontmatter[key].filter((item) => {
                if (typeof item !== "string")
                  return true;
                return !(linkRegexBasename.test(item) || linkRegexFullName.test(item));
              });
            }
          });
        });
      }
    };
    const deleteCanvasFile = async (file) => {
      if (file.extension !== "canvas")
        return;
      if (file.deleted === true)
        return;
      const content = await plugin.app.vault.read(file);
      if (!content)
        return;
      const canvasData = JSON.parse(content);
      if (!canvasData)
        return;
      canvasData.nodes.forEach((node) => {
        if (node.type !== "file")
          return;
        plugin.removeProperty(node, file.name, file.basename);
      });
    };
    const renameCanvasFile = async (file, newPath) => {
      if (file.extension !== "canvas")
        return;
      if (file.deleted === true)
        return;
      const content = await plugin.app.vault.read(file);
      if (!content)
        return;
      const canvasData = JSON.parse(content);
      if (!canvasData)
        return;
      canvasData.nodes.forEach((node) => {
        if (node.type !== "file")
          return;
        plugin.renameProperty(node, file.name, newPath);
      });
    };
    const uninstaller = around(this.app.fileManager.constructor.prototype, {
      trashFile(old) {
        return function(file) {
          deleteCanvasFile(file);
          deleteFile(file);
          return old.call(this, file);
        };
      },
      renameFile(old) {
        return function(file, newPath) {
          renameCanvasFile(file, newPath);
          return old.call(this, file, newPath);
        };
      }
    });
    this.register(uninstaller);
  }
  /**
   * Registers all plugin commands, making them available in the
   * Obsidian command palette.
   *
   * All commands registered here are context-aware and will only be enabled
   * when the active view is a Canvas.
   */
  registerPluginCommands() {
    this.addCommand({
      id: "optimize-edges",
      name: "Adjust edges with shortest path",
      checkCallback: this.ifActiveViewIsCanvas((canvas, canvasData) => {
        this.optimizeEdgesBetweenSelectedNodes(canvas);
      })
    });
    this.addCommand({
      id: "delete-edges",
      name: "Delete edges between selected nodes",
      checkCallback: this.ifActiveViewIsCanvas((canvas, canvasData) => {
        this.deleteEdges(canvas);
      })
    });
    this.addCommand({
      id: "add-link-and-optimize-edge",
      name: "Add edges according the links in notes",
      checkCallback: this.ifActiveViewIsCanvas((canvas, canvasData) => {
        this.createMissingEdgesFromLinks(canvas);
        this.optimizeEdgesBetweenSelectedNodes(canvas);
      })
    });
    this.addCommand({
      id: "remove-canvas-property",
      name: "Remove the property of all nodes in current Canvas",
      checkCallback: this.ifActiveViewIsCanvas((canvas, canvasData) => {
        this.removeAllProperty(canvas, canvasData);
      })
    });
    this.addCommand({
      id: "send-to-canvas",
      name: "Send to Canvas",
      callback: () => {
        this.sendToCanvas.handleSendToCanvas();
      }
    });
    this.addCommand({
      id: "send-to-selected-canvas",
      name: "Send to Selected Canvas",
      callback: () => {
        this.sendToCanvas.handleSendToSelectedCanvas();
      }
    });
    this.addCommand({
      id: "clear-selected-canvas-file",
      name: "Clear selected Canvas file",
      callback: () => {
        this.sendToCanvas.clearSelectedCanvas();
      }
    });
  }
  /**
   * Registers event listeners to implement a "zoom to node" feature.
   *
   * This function's goal is to automatically focus the canvas on the relevant
   * node when a user navigates to the canvas by clicking a link from another
   * file's metadata/properties panel (e.g., a backlink).
   */
  registerFocusCanvas() {
    let clickedSourceFile = null;
    this.registerDomEvent(document, "click", (evt) => {
      const target = evt.target;
      if (target.closest(".metadata-container") || target.closest(".search-result-container")) {
        this.isMetadataClicked = true;
        const activeView = this.app.workspace.getActiveViewOfType(import_obsidian6.ItemView);
        if (activeView && activeView.file) {
          clickedSourceFile = activeView.file.path;
        } else {
          clickedSourceFile = null;
        }
        setTimeout(() => {
          this.isMetadataClicked = false;
          clickedSourceFile = null;
        }, 500);
      }
    }, true);
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", () => {
        Promise.resolve().then(async () => {
          if (this.isMetadataClicked == false || !clickedSourceFile)
            return;
          const activeLeaf = this.app.workspace.getActiveViewOfType(import_obsidian6.ItemView);
          if (!activeLeaf || activeLeaf.getViewType() !== "canvas")
            return;
          const prevFile = clickedSourceFile;
          if (!prevFile)
            return;
          const canvas = activeLeaf.canvas;
          if (!canvas)
            return;
          for (const [key, value] of canvas.nodes) {
            if ((value == null ? void 0 : value.filePath) === prevFile) {
              canvas.select(value);
            }
          }
          setTimeout(() => {
            canvas.zoomToSelection();
          }, 100);
        });
      })
    );
  }
  /**
   * Establishes real-time synchronization to manage frontmatter properties
   * in source files based on their connections within a canvas.
   * This ensures file metadata automatically reflects the
   * visual graph structure as nodes and edges are added, removed, or updated.
   */
  registerCanvasAutoLink() {
    const plugin = this;
    const processNodeUpdate = async (e) => {
      var _a, _b;
      const fromNode = (_a = e == null ? void 0 : e.from) == null ? void 0 : _a.node;
      const toNode = (_b = e == null ? void 0 : e.to) == null ? void 0 : _b.node;
      if (!fromNode || !toNode)
        return;
      if (!(fromNode == null ? void 0 : fromNode.filePath))
        return;
      const fromFile = this.app.vault.getFileByPath(fromNode.filePath);
      if (!fromFile)
        return;
      const canvasName = e.canvas.view.file.basename;
      const resolvedLinks = this.app.metadataCache.resolvedLinks[fromNode.filePath] || {};
      const fromNodeLinks = Object.keys(resolvedLinks);
      const { edges, nodes } = e.canvas.getData();
      const sameFileNodeIds = new Set(nodes.filter((node) => node.file === fromNode.filePath).map((node) => node.id));
      const allRelevantEdges = edges.filter((edge) => sameFileNodeIds.has(edge.fromNode));
      const edgeToNodesFilePathSet = new Set(
        allRelevantEdges.map((edge) => nodes.find((node) => node.id === edge.toNode)).filter((node) => node && node.file).map((node) => node.file)
      );
      const updatePromises = [];
      const getFilePath = (path) => this.app.vault.getFileByPath(path);
      fromNodeLinks.forEach((filePath) => {
        if (!edgeToNodesFilePathSet.has(filePath)) {
          if (filePath === e.canvas.view.file.path)
            return;
          const targetFile = getFilePath(filePath);
          if (!targetFile)
            return;
          let link = this.app.fileManager.generateMarkdownLink(targetFile, filePath).replace(/^!(\[\[.*\]\])$/, "$1");
          updatePromises.push(this.updateFrontmatter(fromFile, link, "remove", canvasName));
        }
      });
      if (toNode == null ? void 0 : toNode.filePath) {
        if (fromNode.filePath !== toNode.filePath) {
          const targetFile = getFilePath(toNode.filePath);
          if (targetFile) {
            let link = this.app.fileManager.generateMarkdownLink(targetFile, toNode.filePath).replace(/^!(\[\[.*\]\])$/, "$1");
            updatePromises.push(this.updateFrontmatter(fromFile, link, "add", canvasName));
          }
        }
      }
      await Promise.all(updatePromises);
    };
    const updateTargetNode = (0, import_obsidian6.debounce)(async (e) => {
      await processNodeUpdate(e);
    }, 500, true);
    const updateTargetNodeImmediate = async (e) => {
      await processNodeUpdate(e);
    };
    const updateOriginalNode = async (edge) => {
      var _a, _b;
      if (!((_a = edge.to.node) == null ? void 0 : _a.filePath) || !((_b = edge.from.node) == null ? void 0 : _b.filePath))
        return;
      const canvasName = edge.canvas.view.file.basename;
      const toNode = edge.to.node;
      const fromNode = edge.from.node;
      const file = this.app.vault.getFileByPath(toNode.filePath);
      if (!file)
        return;
      let link = this.app.fileManager.generateMarkdownLink(file, toNode.filePath);
      link = link.replace(/^!(\[\[.*\]\])$/, "$1");
      if (fromNode == null ? void 0 : fromNode.filePath) {
        const fromFile = this.app.vault.getFileByPath(fromNode.filePath);
        if (!fromFile)
          return;
        const { edges, nodes } = await edge.canvas.getData();
        const sameFileNodes = nodes.filter((node) => node.file === fromNode.filePath);
        const stillHasConnection = edges.some(
          (e) => sameFileNodes.some((node) => e.fromNode === node.id) && e.toNode === toNode.id && !(e.fromNode === fromNode.id && e.toNode === toNode.id)
        );
        if (!stillHasConnection) {
          this.updateFrontmatter(fromFile, link, "remove", canvasName);
        }
      }
    };
    const removeNodeUpdate = async (node) => {
      var _a, _b, _c;
      const resolvedNode = await node;
      if (((_a = resolvedNode == null ? void 0 : resolvedNode.file) == null ? void 0 : _a.extension) !== "md")
        return;
      const canvasFile = (_c = (_b = resolvedNode == null ? void 0 : resolvedNode.canvas) == null ? void 0 : _b.view) == null ? void 0 : _c.file;
      if (!canvasFile || !canvasFile.name)
        return;
      if (resolvedNode == null ? void 0 : resolvedNode.filePath) {
        const canvasData = await resolvedNode.canvas.getData();
        const otherNodes = canvasData.nodes.filter(
          (n) => {
            return n.file === resolvedNode.filePath;
          }
        );
        if (otherNodes.length === 0) {
          let tmpNode = {};
          tmpNode.file = resolvedNode.filePath;
          this.removeProperty(tmpNode, canvasFile.name, canvasFile.basename);
        }
      }
    };
    const addNodeUpdate = async (node) => {
      var _a;
      const resolvedNode = await node;
      if (((_a = resolvedNode == null ? void 0 : resolvedNode.file) == null ? void 0 : _a.extension) !== "md")
        return;
      const canvasFile = resolvedNode.canvas.view.file;
      if (!canvasFile || !canvasFile.name)
        return;
      if (resolvedNode.filePath) {
        let tmpNode = {};
        tmpNode.file = resolvedNode.filePath;
        this.addProperty(tmpNode, canvasFile.name, canvasFile.basename);
      }
    };
    const patchedEdgeConstructors = /* @__PURE__ */ new WeakSet();
    const selfPatched = (edge) => {
      if (patchedEdgeConstructors.has(edge.constructor))
        return;
      patchedEdgeConstructors.add(edge.constructor);
      const uninstaller = around(edge.constructor.prototype, {
        update: (next) => {
          return function(...args) {
            const result = next.call(this, ...args);
            updateTargetNode(this);
            return result;
          };
        }
      });
      plugin.register(uninstaller);
    };
    let canvasPatched = false;
    const patchCanvas = () => {
      var _a;
      if (canvasPatched)
        return false;
      const canvasView = (_a = plugin.app.workspace.getLeavesOfType("canvas")[0]) == null ? void 0 : _a.view;
      if (!(canvasView == null ? void 0 : canvasView.canvas))
        return false;
      const uninstaller = around(canvasView.canvas.constructor.prototype, {
        removeNode(old) {
          return function(node) {
            const result = old.call(this, node);
            if (this.isClearing !== true) {
              removeNodeUpdate(node);
            }
            return result;
          };
        },
        addNode(old) {
          return function(node) {
            const result = old.call(this, node);
            addNodeUpdate(node);
            return result;
          };
        },
        removeEdge(old) {
          return function(edge) {
            const result = old.call(this, edge);
            if (this.isClearing !== true) {
              updateOriginalNode(edge);
            }
            return result;
          };
        },
        addEdge(old) {
          return function(edge) {
            const result = old.call(this, edge);
            selfPatched(edge);
            updateTargetNodeImmediate(edge);
            return result;
          };
        },
        clear(old) {
          return function() {
            this.isClearing = true;
            const result = old.call(this);
            queueMicrotask(() => {
              this.isClearing = false;
            });
            return result;
          };
        }
      });
      plugin.register(uninstaller);
      canvasPatched = true;
      return true;
    };
    const tryToPatch = () => {
      if (patchCanvas()) {
        plugin.detachAutoLinkListeners();
      }
    };
    plugin.autoLinkCheckReference = tryToPatch;
    plugin.app.workspace.on("active-leaf-change", tryToPatch);
    plugin.app.workspace.on("layout-change", tryToPatch);
    plugin.app.workspace.onLayoutReady(tryToPatch);
    tryToPatch();
  }
  registerCanvasExploder() {
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu) => {
        this.exploder.checkAndAddMenu(menu, "Split by Headings");
      })
    );
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu) => {
        this.exploder.checkAndAddMenu(menu, "Split by Headings");
      })
    );
    this.patchCanvasNodeMenu();
  }
  registerCanvasTagImport() {
    this.canvasTagImport.register();
  }
  /**
   * Patches Canvas to add context menu for text nodes (which don't trigger file-menu).
   */
  patchCanvasNodeMenu() {
    const plugin = this;
    let patched = false;
    const tryPatch = () => {
      var _a, _b, _c, _d, _e, _f;
      if (patched)
        return;
      const canvasView = (_b = (_a = this.app.workspace.getLeavesOfType("canvas")) == null ? void 0 : _a[0]) == null ? void 0 : _b.view;
      const anyNode = (_f = (_e = (_d = (_c = canvasView == null ? void 0 : canvasView.canvas) == null ? void 0 : _c.nodes) == null ? void 0 : _d.values()) == null ? void 0 : _e.next()) == null ? void 0 : _f.value;
      if (!anyNode)
        return;
      const basePrototype = Object.getPrototypeOf(Object.getPrototypeOf(anyNode));
      if (!(basePrototype == null ? void 0 : basePrototype.showMenu))
        return;
      const uninstall = around(basePrototype, {
        showMenu: (next) => {
          return function(menu, ...args) {
            const result = next.call(this, menu, ...args);
            if (this.text !== void 0 && !this.file) {
              plugin.exploder.addTextNodeMenu(menu, this);
            }
            return result;
          };
        }
      });
      this.register(uninstall);
      patched = true;
      plugin.app.workspace.offref(leafEvent);
    };
    const leafEvent = this.app.workspace.on("active-leaf-change", tryPatch);
    this.app.workspace.onLayoutReady(tryPatch);
    this.registerEvent(leafEvent);
  }
  /**
   * Installs hooks into the native Canvas prototype to enable automatic height adjustment behavior,
   * allowing nodes to dynamically resize to fit their content in response to specific user gestures
   * on resize handles.
   */
  patchCanvasNodeAutoHeight() {
    var _a, _b;
    if (this.autoHeightUninstaller)
      return false;
    const canvasView = (_b = (_a = this.app.workspace.getLeavesOfType("canvas")) == null ? void 0 : _a.first()) == null ? void 0 : _b.view;
    if (!canvasView)
      return false;
    const canvas = canvasView.canvas;
    if (!canvas)
      return false;
    const anyNode = canvas.nodes.values().next().value;
    if (!anyNode)
      return false;
    const anyNodeConstructor = anyNode.constructor;
    const baseNodePrototype = Object.getPrototypeOf(anyNodeConstructor.prototype);
    const methodsToPatch = {};
    if (baseNodePrototype.onResizeDblclick) {
      methodsToPatch.onResizeDblclick = (originalMethod) => {
        return function(...args) {
          const [, direction] = args;
          if (direction === "bottom") {
            if (this._autoHeightTimer) {
              window.clearTimeout(this._autoHeightTimer);
              this._autoHeightTimer = null;
            }
            this.autoHeightEnabled = true;
          }
          return originalMethod.apply(this, args);
        };
      };
    }
    if (baseNodePrototype.onResizePointerdown) {
      methodsToPatch.onResizePointerdown = (originalMethod) => {
        return function(...args) {
          const [event, direction] = args;
          const result = originalMethod.apply(this, args);
          if (direction === "bottom") {
            if (this._autoHeightTimer) {
              window.clearTimeout(this._autoHeightTimer);
            }
            this._autoHeightTimer = window.setTimeout(() => {
              this.autoHeightEnabled = false;
              this._autoHeightTimer = null;
            }, 300);
          } else if (direction === "right" || direction === "left") {
            if (this.autoHeightEnabled === true) {
              const handlePointerUp = () => {
                window.setTimeout(() => {
                  if (!this.canvas || !this.canvas.nodes.has(this.id))
                    return;
                  if (this.nodeEl && this.nodeEl.classList.contains("is-resizing")) {
                    return;
                  }
                  this.onResizeDblclick(event, "bottom");
                }, 0);
              };
              window.addEventListener("pointerup", handlePointerUp, { once: true });
            }
          }
          return result;
        };
      };
    }
    if (baseNodePrototype.blur) {
      methodsToPatch.blur = (originalMethod) => {
        return function(...args) {
          const result = originalMethod.apply(this, args);
          if (this.autoHeightEnabled) {
            setTimeout(() => {
              if (typeof this.onResizeDblclick === "function") {
                const mockEvent = {
                  preventDefault: () => {
                  },
                  stopPropagation: () => {
                  }
                };
                this.onResizeDblclick(mockEvent, "bottom");
              }
            }, 300);
          }
          return result;
        };
      };
    }
    if (Object.keys(methodsToPatch).length === 0)
      return false;
    this.autoHeightUninstaller = around(baseNodePrototype, methodsToPatch);
    this.register(this.autoHeightUninstaller);
    return true;
  }
  registerCanvasNodeAutoHeightPatcher() {
    const tryToPatch = () => {
      const success = this.patchCanvasNodeAutoHeight();
      if (success) {
        this.detachAutoHeightPatcherListeners();
      }
    };
    this.autoHeightCheckReference = tryToPatch;
    this.app.workspace.on("active-leaf-change", tryToPatch);
    this.app.workspace.on("layout-change", tryToPatch);
    this.app.workspace.onLayoutReady(tryToPatch);
    tryToPatch();
  }
  detachAutoHeightPatcherListeners() {
    if (this.autoHeightCheckReference) {
      this.app.workspace.off("active-leaf-change", this.autoHeightCheckReference);
      this.app.workspace.off("layout-change", this.autoHeightCheckReference);
      this.autoHeightCheckReference = null;
    }
  }
  detachAutoLinkListeners() {
    if (this.autoLinkCheckReference) {
      this.app.workspace.off("active-leaf-change", this.autoLinkCheckReference);
      this.app.workspace.off("layout-change", this.autoLinkCheckReference);
      this.autoLinkCheckReference = null;
    }
  }
  /**
   * Writes the user's configured default sizes into a Canvas instance's config so that
   * every native creation path (double-click, paste, programmatic createTextNode/createFileNode)
   * picks them up. Touches in-memory state only.
   */
  applyDefaultNodeSizeToCanvas(canvas) {
    if (!(canvas == null ? void 0 : canvas.config))
      return;
    canvas.config.defaultTextNodeDimensions = {
      width: this.settings.defaultTextNodeWidth,
      height: this.settings.defaultTextNodeHeight
    };
    canvas.config.defaultFileNodeDimensions = {
      width: this.settings.defaultFileNodeWidth,
      height: this.settings.defaultFileNodeHeight
    };
  }
  applyDefaultNodeSizeToAllOpenCanvases() {
    var _a;
    for (const leaf of this.app.workspace.getLeavesOfType("canvas")) {
      const canvas = (_a = leaf.view) == null ? void 0 : _a.canvas;
      if (canvas)
        this.applyDefaultNodeSizeToCanvas(canvas);
    }
  }
  registerCanvasDefaultNodeSize() {
    const apply = () => this.applyDefaultNodeSizeToAllOpenCanvases();
    this.registerEvent(this.app.workspace.on("active-leaf-change", apply));
    this.registerEvent(this.app.workspace.on("layout-change", apply));
    this.app.workspace.onLayoutReady(apply);
    apply();
  }
  /**
   * Patches Canvas.prototype.dragTempNode so dragging a note in from the file explorer
   * uses the user's configured file-node size instead of whatever Obsidian's drag handler
   * computed upstream of canvas.config.
   */
  patchCanvasDragTempNode() {
    var _a, _b, _c, _d;
    if (this.dragTempNodeUninstaller)
      return false;
    const canvasView = (_b = (_a = this.app.workspace.getLeavesOfType("canvas")) == null ? void 0 : _a.first()) == null ? void 0 : _b.view;
    const canvas = canvasView == null ? void 0 : canvasView.canvas;
    if (!((_d = (_c = canvas == null ? void 0 : canvas.constructor) == null ? void 0 : _c.prototype) == null ? void 0 : _d.dragTempNode))
      return false;
    const plugin = this;
    const uninstall = around(canvas.constructor.prototype, {
      dragTempNode(orig) {
        return function(dragEvent, _nodeSize, onDropped) {
          const overridden = {
            width: plugin.settings.defaultFileNodeWidth,
            height: plugin.settings.defaultFileNodeHeight
          };
          return orig.call(this, dragEvent, overridden, onDropped);
        };
      }
    });
    this.dragTempNodeUninstaller = uninstall;
    this.register(uninstall);
    return true;
  }
  registerCanvasDragTempNodePatcher() {
    const tryToPatch = () => {
      if (this.patchCanvasDragTempNode()) {
        this.detachDragTempNodeListeners();
      }
    };
    this.dragTempNodeCheckReference = tryToPatch;
    this.app.workspace.on("active-leaf-change", tryToPatch);
    this.app.workspace.on("layout-change", tryToPatch);
    this.app.workspace.onLayoutReady(tryToPatch);
    tryToPatch();
  }
  detachDragTempNodeListeners() {
    if (this.dragTempNodeCheckReference) {
      this.app.workspace.off("active-leaf-change", this.dragTempNodeCheckReference);
      this.app.workspace.off("layout-change", this.dragTempNodeCheckReference);
      this.dragTempNodeCheckReference = null;
    }
  }
  createEdge(node1, node2) {
    const node1CenterX = node1.x + node1.width / 2;
    const node1CenterY = node1.y + node1.height / 2;
    const node2CenterX = node2.x + node2.width / 2;
    const node2CenterY = node2.y + node2.height / 2;
    const angle = Math.atan2(node2CenterY - node1CenterY, node2CenterX - node1CenterX) * 180 / Math.PI;
    const normalizedAngle = angle < 0 ? angle + 360 : angle;
    let fromSide;
    let toSide;
    if (normalizedAngle >= 315 || normalizedAngle < 45) {
      fromSide = "right";
      toSide = "left";
    } else if (normalizedAngle >= 45 && normalizedAngle < 135) {
      fromSide = "bottom";
      toSide = "top";
    } else if (normalizedAngle >= 135 && normalizedAngle < 225) {
      fromSide = "left";
      toSide = "right";
    } else {
      fromSide = "top";
      toSide = "bottom";
    }
    const edgeData = {
      id: randomId(16),
      fromSide,
      fromNode: node1.id,
      toSide,
      toNode: node2.id
    };
    return edgeData;
  }
  /**
   * Performs a comprehensive cleanup on all canvas files when the plugin is
   * unloaded, ensuring any custom properties or data managed by this plugin
   * are removed from the vault.
   */
  async onunload() {
    if (this.canvasStackInterval !== null) {
      clearInterval(this.canvasStackInterval);
      this.canvasStackInterval = null;
    }
    document.body.classList.remove("enhanced-canvas-enabled");
    this.detachAutoHeightPatcherListeners();
    this.detachAutoLinkListeners();
    this.detachDragTempNodeListeners();
    this.sendToCanvas.clearSelectedCanvas(false);
    try {
      const canvasFiles = this.app.vault.getFiles().filter((file) => file.extension === "canvas");
      await Promise.all(canvasFiles.map(async (canvasFile) => {
        try {
          const content = await this.app.vault.read(canvasFile);
          const canvasData = JSON.parse(content);
          const tempCanvas = {
            view: {
              file: canvasFile
            },
            setData: () => {
            },
            requestSave: () => {
            }
          };
          await this.removeAllProperty(tempCanvas, canvasData);
        } catch (error) {
          console.error("Enhanced Canvas: Failed to remove property from canvas", error);
          return;
        }
      }));
    } catch (error) {
      console.error("Enhanced Canvas: Error during bulk property removal", error);
      return;
    }
  }
};
var EnhancedCanvasSettingTab = class extends import_obsidian6.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian6.Setting(containerEl).setName("Enable Frontmatter Synchronization").setDesc(
      "When enabled, canvas nodes and edges are mapped to file metadata (properties). "
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableFrontmatter).onChange(async (value) => {
        if (!value) {
          try {
            const canvasFiles = this.plugin.app.vault.getFiles().filter((file) => file.extension === "canvas");
            const failedFiles = [];
            await Promise.all(canvasFiles.map(async (canvasFile) => {
              try {
                const content = await this.plugin.app.vault.read(canvasFile);
                const canvasData = JSON.parse(content);
                const tempCanvas = {
                  view: {
                    file: canvasFile
                  },
                  setData: () => {
                  },
                  requestSave: () => {
                  }
                };
                await this.plugin.removeAllProperty(tempCanvas, canvasData);
              } catch (error) {
                console.error("Enhanced Canvas: Settings cleanup failed for file", canvasFile.path, error);
                failedFiles.push(canvasFile.path);
              }
            }));
            if (failedFiles.length > 0) {
              new import_obsidian6.Notice(`Failed to clean up properties for ${failedFiles.length} canvases. Check console.`);
              toggle.setValue(true);
              return;
            }
          } catch (error) {
            console.error("Enhanced Canvas: Settings cleanup loop failed", error);
            new import_obsidian6.Notice("Failed to initiate properties cleanup. Aborting disable.");
            toggle.setValue(true);
            return;
          }
        }
        this.plugin.settings.enableFrontmatter = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("Enable Custom Visuals & CSS").setDesc(
      "When enabled, hide the metadata panel (properties) inside Canvas Node (and embedded notes and iframe previews)."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableCustomCSS).onChange(async (value) => {
        this.plugin.settings.enableCustomCSS = value;
        await this.plugin.saveSettings();
        this.plugin.toggleCSSClass(value);
      })
    );
    const MIN_NODE_DIMENSION = 50;
    const MAX_NODE_DIMENSION = 5e3;
    containerEl.createEl("h3", { text: "Default node size" });
    const sizeRow = (name, desc, key) => {
      new import_obsidian6.Setting(containerEl).setName(name).setDesc(desc).addText(
        (text) => text.setValue(String(this.plugin.settings[key])).onChange(async (raw) => {
          const n = Number.parseInt(raw, 10);
          if (!Number.isFinite(n))
            return;
          if (n < MIN_NODE_DIMENSION || n > MAX_NODE_DIMENSION)
            return;
          this.plugin.settings[key] = n;
          await this.plugin.saveSettings();
          this.plugin.applyDefaultNodeSizeToAllOpenCanvases();
        })
      );
    };
    sizeRow("Text node width", "Initial width (px) for new text cards. 50\u20135000.", "defaultTextNodeWidth");
    sizeRow("Text node height", "Initial height (px) for new text cards. 50\u20135000.", "defaultTextNodeHeight");
    sizeRow("File node width", "Initial width (px) for new file nodes. 50\u20135000.", "defaultFileNodeWidth");
    sizeRow("File node height", "Initial height (px) for new file nodes. 50\u20135000.", "defaultFileNodeHeight");
  }
};


/* nosourcemap */