/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var i=Object.defineProperty;var u=Object.getOwnPropertyDescriptor;var h=Object.getOwnPropertyNames;var k=Object.prototype.hasOwnProperty;var g=(t,o)=>{for(var s in o)i(t,s,{get:o[s],enumerable:!0})},m=(t,o,s,c)=>{if(o&&typeof o=="object"||typeof o=="function")for(let n of h(o))!k.call(t,n)&&n!==s&&i(t,n,{get:()=>o[n],enumerable:!(c=u(o,n))||c.enumerable});return t};var p=t=>m(i({},"__esModule",{value:!0}),t);var x={};g(x,{default:()=>e});module.exports=p(x);var r=require("obsidian"),d=require("child_process"),e=class extends r.Plugin{async onload(){this.registerMarkdownCodeBlockProcessor("runsh",this.processRunshBlock.bind(this))}async processRunshBlock(o,s,c){let[n,...l]=o.split("%%%"),a=s.createEl("button",{text:l.length>0?l.join(" "):"Run command"});a.setAttribute("title",n),a.on("click","button",()=>{f(n)})}},f=async t=>{new r.Notice("Running: "+t),(0,d.spawn)(t,{shell:!0,detached:!0,stdio:"ignore"})};

/* nosourcemap */