/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DetailedCanvasPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian7 = require("obsidian");

// src/constants.ts
var OPENAI_BASE_URL = "https://api.openai.com/v1";
var OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1";
var GROQ_BASE_URL = "https://api.groq.com/openai/v1";
var CLAUDE_BASE_URL = "https://api.anthropic.com/v1";
var DEFAULT_OPENAI_MODEL = "gpt-4o-mini";
var DEFAULT_OPENROUTER_MODEL = "openai/gpt-4o-mini";
var DEFAULT_GROQ_MODEL = "llama-3.1-8b-instant";
var DEFAULT_CLAUDE_MODEL = "claude-3-haiku-20240307";
var ENV_OPENAI_API_KEY = "OPENAI_API_KEY";
var ENV_OPENROUTER_API_KEY = "OPENROUTER_API_KEY";
var ENV_GROQ_API_KEY = "GROQ_API_KEY";
var ENV_ANTHROPIC_API_KEY = "ANTHROPIC_API_KEY";
var CLAUDE_MODELS = [
  "claude-3-haiku-20240307",
  "claude-3-5-haiku-20241022",
  "claude-3-5-sonnet-20241022",
  "claude-3-5-sonnet-20240620",
  "claude-sonnet-4-20250514"
];
var OLLAMA_GENERATE_ENDPOINT = "/api/generate";
var OLLAMA_TAGS_ENDPOINT = "/api/tags";
var DEFAULT_SETTINGS = {
  ollamaEndpoint: "http://localhost:11434",
  ollamaModel: "llama3.2",
  autoEnrichOnPaste: true,
  notesFolder: "Canvas Notes",
  descriptionPrompt: "Summarize this web page content in 2-3 sentences. Focus on the main topic and key points. Be concise and informative.",
  maxDescriptionLength: 500,
  showNotifications: true,
  aiProvider: "ollama",
  openaiApiKey: "",
  openaiModel: DEFAULT_OPENAI_MODEL,
  openaiBaseUrl: "",
  openrouterApiKey: "",
  openrouterModel: DEFAULT_OPENROUTER_MODEL,
  groqApiKey: "",
  groqModel: DEFAULT_GROQ_MODEL,
  claudeApiKey: "",
  claudeModel: DEFAULT_CLAUDE_MODEL,
  useEnvVariables: false
};

// src/settings.ts
var import_obsidian4 = require("obsidian");

// src/services/ollama.ts
var import_obsidian = require("obsidian");
var OllamaClient = class {
  constructor(endpoint, model) {
    this.endpoint = endpoint;
    this.model = model;
  }
  /**
   * Generate text using Ollama's /api/generate endpoint
   * @param prompt The prompt to send to the model
   * @param context Additional context for the generation
   * @returns The generated text response
   * @throws Error if the request fails or times out
   */
  async generate(prompt, context) {
    try {
      const fullPrompt = context ? `Context:
${context}

${prompt}` : prompt;
      const request = {
        model: this.model,
        prompt: fullPrompt,
        stream: false,
        options: {
          temperature: 0.7,
          num_predict: 500
        }
      };
      const response = await (0, import_obsidian.requestUrl)({
        url: `${this.endpoint}${OLLAMA_GENERATE_ENDPOINT}`,
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify(request),
        throw: false
      });
      if (response.status !== 200) {
        throw new Error(
          `Ollama API request failed with status ${response.status}: ${response.text}`
        );
      }
      const data = response.json;
      if (!data.response) {
        throw new Error("Invalid response from Ollama API: missing response field");
      }
      return data.response.trim();
    } catch (error) {
      if (error instanceof Error) {
        throw new Error(`Failed to generate text: ${error.message}`);
      }
      throw new Error("Failed to generate text: Unknown error");
    }
  }
  /**
   * Check if Ollama is running and accessible
   * @returns true if connection is successful, false otherwise
   */
  async checkConnection() {
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url: `${this.endpoint}${OLLAMA_TAGS_ENDPOINT}`,
        method: "GET",
        throw: false
      });
      return response.status === 200;
    } catch (error) {
      console.debug("Failed to check Ollama connection:", error);
      return false;
    }
  }
  /**
   * Get list of available models from Ollama
   * @returns Array of model names
   * @throws Error if the request fails
   */
  async getModels() {
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url: `${this.endpoint}${OLLAMA_TAGS_ENDPOINT}`,
        method: "GET",
        throw: false
      });
      if (response.status !== 200) {
        throw new Error(
          `Failed to fetch models: status ${response.status}`
        );
      }
      const data = response.json;
      if (!data.models || !Array.isArray(data.models)) {
        throw new Error("Invalid response from Ollama API: missing models field");
      }
      return data.models.map((model) => model.name);
    } catch (error) {
      if (error instanceof Error) {
        throw new Error(`Failed to fetch models: ${error.message}`);
      }
      throw new Error("Failed to fetch models: Unknown error");
    }
  }
  /**
   * Update the endpoint URL
   * @param endpoint New endpoint URL
   */
  setEndpoint(endpoint) {
    this.endpoint = endpoint;
  }
  /**
   * Update the model name
   * @param model New model name
   */
  setModel(model) {
    this.model = model;
  }
  /**
   * Get current endpoint
   */
  getEndpoint() {
    return this.endpoint;
  }
  /**
   * Get current model
   */
  getModel() {
    return this.model;
  }
};

// src/services/openai-provider.ts
var import_obsidian2 = require("obsidian");
var OpenAICompatibleProvider = class {
  constructor(apiKey, model, baseUrl, extraHeaders = {}) {
    this.apiKey = apiKey;
    this.model = model;
    this.baseUrl = baseUrl;
    this.extraHeaders = extraHeaders;
  }
  async generate(prompt, context) {
    const fullPrompt = context ? `Context:
${context}

${prompt}` : prompt;
    const request = {
      model: this.model,
      messages: [
        { role: "user", content: fullPrompt }
      ],
      max_tokens: 500,
      temperature: 0.7
    };
    const response = await (0, import_obsidian2.requestUrl)({
      url: `${this.baseUrl}/chat/completions`,
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${this.apiKey}`,
        ...this.extraHeaders
      },
      body: JSON.stringify(request),
      throw: false
    });
    if (response.status !== 200) {
      throw new Error(`API request failed with status ${response.status}: ${response.text}`);
    }
    const data = response.json;
    if (!data.choices || data.choices.length === 0) {
      throw new Error("Invalid response: no choices returned");
    }
    return data.choices[0].message.content.trim();
  }
  async checkConnection() {
    try {
      const response = await (0, import_obsidian2.requestUrl)({
        url: `${this.baseUrl}/models`,
        method: "GET",
        headers: {
          "Authorization": `Bearer ${this.apiKey}`,
          ...this.extraHeaders
        },
        throw: false
      });
      return response.status === 200;
    } catch (e) {
      return false;
    }
  }
  async getModels() {
    try {
      const response = await (0, import_obsidian2.requestUrl)({
        url: `${this.baseUrl}/models`,
        method: "GET",
        headers: {
          "Authorization": `Bearer ${this.apiKey}`,
          ...this.extraHeaders
        },
        throw: false
      });
      if (response.status !== 200) {
        return [this.model];
      }
      const data = response.json;
      if (!data.data || !Array.isArray(data.data)) {
        return [this.model];
      }
      return data.data.map((m) => m.id);
    } catch (e) {
      return [this.model];
    }
  }
};

// src/services/claude-provider.ts
var import_obsidian3 = require("obsidian");
var ClaudeProvider = class {
  constructor(apiKey, model) {
    this.apiKey = apiKey;
    this.model = model;
  }
  async generate(prompt, context) {
    const fullPrompt = context ? `Context:
${context}

${prompt}` : prompt;
    const request = {
      model: this.model,
      max_tokens: 500,
      messages: [
        { role: "user", content: fullPrompt }
      ]
    };
    const response = await (0, import_obsidian3.requestUrl)({
      url: `${CLAUDE_BASE_URL}/messages`,
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": this.apiKey,
        "anthropic-version": "2023-06-01"
      },
      body: JSON.stringify(request),
      throw: false
    });
    if (response.status !== 200) {
      throw new Error(`Claude API request failed with status ${response.status}: ${response.text}`);
    }
    const data = response.json;
    if (!data.content || data.content.length === 0) {
      throw new Error("Invalid response from Claude API: no content returned");
    }
    const textBlock = data.content.find((block) => block.type === "text");
    if (!textBlock) {
      throw new Error("Invalid response from Claude API: no text content");
    }
    return textBlock.text.trim();
  }
  async checkConnection() {
    try {
      const request = {
        model: this.model,
        max_tokens: 1,
        messages: [
          { role: "user", content: "Hi" }
        ]
      };
      const response = await (0, import_obsidian3.requestUrl)({
        url: `${CLAUDE_BASE_URL}/messages`,
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-api-key": this.apiKey,
          "anthropic-version": "2023-06-01"
        },
        body: JSON.stringify(request),
        throw: false
      });
      return response.status === 200;
    } catch (e) {
      return false;
    }
  }
  getModels() {
    return Promise.resolve(CLAUDE_MODELS);
  }
};

// src/services/provider-factory.ts
function getApiKey(storedKey, envVarName, useEnv) {
  if (useEnv && typeof process !== "undefined" && process.env) {
    const envKey = process.env[envVarName];
    if (envKey)
      return envKey;
  }
  return storedKey;
}
function createProvider(settings) {
  switch (settings.aiProvider) {
    case "openai": {
      const apiKey = getApiKey(settings.openaiApiKey, ENV_OPENAI_API_KEY, settings.useEnvVariables);
      const baseUrl = settings.openaiBaseUrl || OPENAI_BASE_URL;
      return new OpenAICompatibleProvider(apiKey, settings.openaiModel, baseUrl);
    }
    case "openrouter": {
      const apiKey = getApiKey(settings.openrouterApiKey, ENV_OPENROUTER_API_KEY, settings.useEnvVariables);
      return new OpenAICompatibleProvider(apiKey, settings.openrouterModel, OPENROUTER_BASE_URL, {
        "HTTP-Referer": "https://obsidian.md"
      });
    }
    case "groq": {
      const apiKey = getApiKey(settings.groqApiKey, ENV_GROQ_API_KEY, settings.useEnvVariables);
      return new OpenAICompatibleProvider(apiKey, settings.groqModel, GROQ_BASE_URL);
    }
    case "claude": {
      const apiKey = getApiKey(settings.claudeApiKey, ENV_ANTHROPIC_API_KEY, settings.useEnvVariables);
      return new ClaudeProvider(apiKey, settings.claudeModel);
    }
    case "ollama":
    default:
      return new OllamaClient(settings.ollamaEndpoint, settings.ollamaModel);
  }
}

// src/settings.ts
var DetailedCanvasSettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian4.Setting(containerEl).setName("AI provider").setHeading();
    new import_obsidian4.Setting(containerEl).setName("Provider").setDesc("Choose your AI provider for generating descriptions").addDropdown((dropdown) => {
      dropdown.addOption("ollama", "Ollama (local)").addOption("openai", "OpenAI").addOption("claude", "Claude (Anthropic)").addOption("openrouter", "OpenRouter").addOption("groq", "Groq").setValue(this.plugin.settings.aiProvider).onChange(async (value) => {
        this.plugin.settings.aiProvider = value;
        await this.plugin.saveSettings();
        this.display();
      });
    });
    this.displayProviderSettings(containerEl);
    new import_obsidian4.Setting(containerEl).setName("Behavior").setHeading();
    new import_obsidian4.Setting(containerEl).setName("Auto-enrich on paste").setDesc("Automatically enrich link cards when added to canvas").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoEnrichOnPaste).onChange(async (value) => {
      this.plugin.settings.autoEnrichOnPaste = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian4.Setting(containerEl).setName("Notes folder").setDesc("Folder where generated notes will be stored").addText((text) => text.setPlaceholder(DEFAULT_SETTINGS.notesFolder).setValue(this.plugin.settings.notesFolder).onChange(async (value) => {
      this.plugin.settings.notesFolder = value || DEFAULT_SETTINGS.notesFolder;
      await this.plugin.saveSettings();
    }));
    new import_obsidian4.Setting(containerEl).setName("Show notifications").setDesc("Display progress notifications during enrichment").addToggle((toggle) => toggle.setValue(this.plugin.settings.showNotifications).onChange(async (value) => {
      this.plugin.settings.showNotifications = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian4.Setting(containerEl).setName("Max description length").setDesc("Maximum number of characters for generated descriptions").addText((text) => text.setPlaceholder(DEFAULT_SETTINGS.maxDescriptionLength.toString()).setValue(this.plugin.settings.maxDescriptionLength.toString()).onChange(async (value) => {
      const numValue = parseInt(value, 10);
      if (!isNaN(numValue) && numValue > 0) {
        this.plugin.settings.maxDescriptionLength = numValue;
        await this.plugin.saveSettings();
      }
    }));
    new import_obsidian4.Setting(containerEl).setName("Advanced").setHeading();
    new import_obsidian4.Setting(containerEl).setName("AI prompt").setDesc("Instructions for the AI when generating descriptions. Use this to customize the style and content of generated summaries.").addTextArea((text) => {
      text.setPlaceholder(DEFAULT_SETTINGS.descriptionPrompt).setValue(this.plugin.settings.descriptionPrompt).onChange(async (value) => {
        this.plugin.settings.descriptionPrompt = value || DEFAULT_SETTINGS.descriptionPrompt;
        await this.plugin.saveSettings();
      });
      text.inputEl.rows = 6;
      text.inputEl.cols = 50;
      return text;
    });
    new import_obsidian4.Setting(containerEl).setName("Use environment variables").setDesc("Read API keys from environment variables (OPENAI_API_KEY, ANTHROPIC_API_KEY, OPENROUTER_API_KEY, GROQ_API_KEY). Stored keys are used as fallback.").addToggle((toggle) => toggle.setValue(this.plugin.settings.useEnvVariables).onChange(async (value) => {
      this.plugin.settings.useEnvVariables = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian4.Setting(containerEl).setName("Reset to defaults").setDesc("Reset all settings to their default values").addButton((button) => button.setButtonText("Reset").setWarning().onClick(() => {
      new ConfirmResetModal(this.app, () => {
        Object.assign(this.plugin.settings, DEFAULT_SETTINGS);
        void this.plugin.saveSettings().then(() => {
          this.display();
          new import_obsidian4.Notice("Settings reset to defaults");
        });
      }).open();
    }));
  }
  displayProviderSettings(containerEl) {
    switch (this.plugin.settings.aiProvider) {
      case "ollama":
        this.displayOllamaSettings(containerEl);
        break;
      case "openai":
        this.displayOpenAISettings(containerEl);
        break;
      case "claude":
        this.displayClaudeSettings(containerEl);
        break;
      case "openrouter":
        this.displayOpenRouterSettings(containerEl);
        break;
      case "groq":
        this.displayGroqSettings(containerEl);
        break;
    }
  }
  displayOllamaSettings(containerEl) {
    new import_obsidian4.Setting(containerEl).setName("Ollama endpoint").setDesc("URL of your Ollama server (e.g., http://localhost:11434)").addText((text) => text.setPlaceholder(DEFAULT_SETTINGS.ollamaEndpoint).setValue(this.plugin.settings.ollamaEndpoint).onChange(async (value) => {
      this.plugin.settings.ollamaEndpoint = value || DEFAULT_SETTINGS.ollamaEndpoint;
      await this.plugin.saveSettings();
    })).addButton((button) => button.setButtonText("Test connection").onClick(async () => {
      await this.testConnection();
    }));
    const modelSetting = new import_obsidian4.Setting(containerEl).setName("Model").setDesc("Ollama model for generating descriptions");
    modelSetting.addDropdown(async (dropdown) => {
      dropdown.addOption(
        this.plugin.settings.ollamaModel,
        this.plugin.settings.ollamaModel
      );
      try {
        const provider = createProvider(this.plugin.settings);
        const models = await provider.getModels();
        dropdown.selectEl.empty();
        if (models.length === 0) {
          dropdown.addOption("", "No models available");
          dropdown.setDisabled(true);
        } else {
          for (const model of models) {
            dropdown.addOption(model, model);
          }
          dropdown.setValue(this.plugin.settings.ollamaModel);
        }
      } catch (e) {
        dropdown.selectEl.empty();
        dropdown.addOption("", "Failed to fetch models");
        dropdown.addOption(
          this.plugin.settings.ollamaModel,
          this.plugin.settings.ollamaModel
        );
        dropdown.setValue(this.plugin.settings.ollamaModel);
      }
      dropdown.onChange(async (value) => {
        this.plugin.settings.ollamaModel = value;
        await this.plugin.saveSettings();
      });
    });
    modelSetting.addButton((button) => button.setButtonText("Refresh").setTooltip("Refresh available models").onClick(() => {
      this.display();
    }));
  }
  displayOpenAISettings(containerEl) {
    this.addApiKeySetting(containerEl, "OpenAI API key", "openaiApiKey");
    this.addModelDropdown(containerEl, "openaiModel", DEFAULT_SETTINGS.openaiModel);
    new import_obsidian4.Setting(containerEl).setName("Custom base URL").setDesc("Optional: override the API base URL (for Azure OpenAI or compatible APIs)").addText((text) => text.setPlaceholder("https://api.openai.com/v1").setValue(this.plugin.settings.openaiBaseUrl).onChange(async (value) => {
      this.plugin.settings.openaiBaseUrl = value;
      await this.plugin.saveSettings();
    }));
    this.addTestConnectionButton(containerEl);
  }
  displayClaudeSettings(containerEl) {
    this.addApiKeySetting(containerEl, "Anthropic API key", "claudeApiKey");
    new import_obsidian4.Setting(containerEl).setName("Model").setDesc("Claude model to use").addDropdown((dropdown) => {
      for (const model of CLAUDE_MODELS) {
        dropdown.addOption(model, model);
      }
      dropdown.setValue(this.plugin.settings.claudeModel);
      dropdown.onChange(async (value) => {
        this.plugin.settings.claudeModel = value;
        await this.plugin.saveSettings();
      });
    });
    this.addTestConnectionButton(containerEl);
  }
  displayOpenRouterSettings(containerEl) {
    this.addApiKeySetting(containerEl, "OpenRouter API key", "openrouterApiKey");
    this.addModelDropdown(containerEl, "openrouterModel", DEFAULT_SETTINGS.openrouterModel);
    this.addTestConnectionButton(containerEl);
  }
  displayGroqSettings(containerEl) {
    this.addApiKeySetting(containerEl, "Groq API key", "groqApiKey");
    this.addModelDropdown(containerEl, "groqModel", DEFAULT_SETTINGS.groqModel);
    this.addTestConnectionButton(containerEl);
  }
  addModelDropdown(containerEl, settingsKey, defaultModel) {
    const modelSetting = new import_obsidian4.Setting(containerEl).setName("Model").setDesc("Select a model or type a custom model name");
    modelSetting.addDropdown(async (dropdown) => {
      const currentModel = this.plugin.settings[settingsKey] || defaultModel;
      dropdown.addOption(currentModel, currentModel);
      try {
        const provider = createProvider(this.plugin.settings);
        const models = await provider.getModels();
        dropdown.selectEl.empty();
        if (models.length === 0) {
          dropdown.addOption(currentModel, currentModel);
        } else {
          for (const model of models) {
            dropdown.addOption(model, model);
          }
        }
        dropdown.setValue(currentModel);
      } catch (e) {
        dropdown.selectEl.empty();
        dropdown.addOption(currentModel, currentModel);
        dropdown.setValue(currentModel);
      }
      dropdown.onChange(async (value) => {
        this.plugin.settings[settingsKey] = value;
        await this.plugin.saveSettings();
      });
    });
    modelSetting.addButton((button) => button.setButtonText("Refresh").setTooltip("Refresh available models").onClick(() => {
      this.display();
    }));
  }
  addApiKeySetting(containerEl, name, settingsKey) {
    const setting = new import_obsidian4.Setting(containerEl).setName(name).setDesc("API keys are stored locally in your vault's plugin data. For additional security, enable environment variables in the advanced section.");
    setting.addText((text) => {
      text.inputEl.type = "password";
      text.inputEl.addClass("detailed-canvas-api-key-input");
      text.setPlaceholder("Enter API key...").setValue(this.plugin.settings[settingsKey]).onChange(async (value) => {
        this.plugin.settings[settingsKey] = value;
        await this.plugin.saveSettings();
      });
    });
    setting.addButton((button) => {
      let visible = false;
      button.setIcon("eye").setTooltip("Show/hide API key").onClick(() => {
        visible = !visible;
        const inputEl = setting.controlEl.querySelector("input");
        if (inputEl) {
          inputEl.type = visible ? "text" : "password";
        }
        button.setIcon(visible ? "eye-off" : "eye");
      });
    });
  }
  addTestConnectionButton(containerEl) {
    new import_obsidian4.Setting(containerEl).addButton((button) => button.setButtonText("Test connection").onClick(async () => {
      await this.testConnection();
    }));
  }
  async testConnection() {
    try {
      const provider = createProvider(this.plugin.settings);
      const isConnected = await provider.checkConnection();
      if (isConnected) {
        new import_obsidian4.Notice("Connection successful!");
      } else {
        new import_obsidian4.Notice("Connection failed. Check your settings and API key.");
      }
    } catch (error) {
      const message = error instanceof Error ? error.message : "Unknown error";
      new import_obsidian4.Notice(`Connection error: ${message}`);
    }
  }
};
var ConfirmResetModal = class extends import_obsidian4.Modal {
  constructor(app, onConfirm) {
    super(app);
    this.onConfirm = onConfirm;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("p", {
      text: "Are you sure you want to reset all settings to their default values? This cannot be undone."
    });
    new import_obsidian4.Setting(contentEl).addButton((btn) => btn.setButtonText("Cancel").onClick(() => this.close())).addButton((btn) => btn.setButtonText("Reset").setWarning().onClick(() => {
      this.onConfirm();
      this.close();
    }));
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/services/scraper.ts
var import_obsidian5 = require("obsidian");
var _ScraperService = class _ScraperService {
  /**
   * Scrape metadata and content from a URL
   * @param url - The URL to scrape
   * @returns UrlMetadata with extracted information
   */
  async scrape(url) {
    try {
      const host = new URL(url).hostname.toLowerCase();
      if (_ScraperService.TWITTER_HOSTS.includes(host)) {
        return await this.scrapeTwitter(url);
      }
      const response = await (0, import_obsidian5.requestUrl)({
        url,
        method: "GET",
        throw: false
      });
      if (response.status !== 200) {
        console.warn(`Failed to fetch URL ${url}: HTTP ${response.status}`);
        return this.createEmptyMetadata(url);
      }
      const parser = new DOMParser();
      const doc = parser.parseFromString(response.text, "text/html");
      const baseUrl = new URL(url).origin;
      const title = this.extractTitle(doc);
      const description = this.extractDescription(doc);
      const ogImageCandidate = this.extractImage(doc, baseUrl);
      const ogImage = ogImageCandidate ? await this.validateImageUrl(ogImageCandidate) : null;
      const siteName = this.extractMeta(doc, "og:site_name");
      const favicon = this.extractFavicon(doc, baseUrl);
      const textContent = this.extractTextContent(doc);
      return {
        url,
        title,
        description,
        ogImage,
        siteName,
        favicon,
        textContent
      };
    } catch (error) {
      console.warn(`Error scraping URL ${url}:`, error);
      return this.createEmptyMetadata(url);
    }
  }
  /**
   * Scrape X/Twitter URLs via fxtwitter JSON API
   */
  async scrapeTwitter(originalUrl) {
    var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j, _k, _l, _m, _n, _o, _p, _q;
    const match = originalUrl.match(_ScraperService.TWITTER_STATUS_RE);
    if (!match) {
      return this.createEmptyMetadata(originalUrl);
    }
    const [, screenName, tweetId] = match;
    const apiUrl = `https://api.fxtwitter.com/${screenName}/status/${tweetId}`;
    try {
      const response = await (0, import_obsidian5.requestUrl)({
        url: apiUrl,
        method: "GET",
        headers: { "User-Agent": "DetailedCanvas-ObsidianPlugin/1.0" },
        throw: false
      });
      if (response.status !== 200) {
        console.warn(`fxtwitter API returned ${response.status} for ${originalUrl}`);
        return this.createEmptyMetadata(originalUrl);
      }
      const data = response.json;
      const tweet = data == null ? void 0 : data.tweet;
      if (!tweet) {
        return this.createEmptyMetadata(originalUrl);
      }
      let ogImage = null;
      if (((_b = (_a = tweet.media) == null ? void 0 : _a.photos) == null ? void 0 : _b.length) > 0) {
        ogImage = (_c = tweet.media.photos[0].url) != null ? _c : null;
      } else if (((_e = (_d = tweet.media) == null ? void 0 : _d.videos) == null ? void 0 : _e.length) > 0) {
        ogImage = (_f = tweet.media.videos[0].thumbnail_url) != null ? _f : null;
      } else if ((_h = (_g = tweet.media) == null ? void 0 : _g.external) == null ? void 0 : _h.thumbnail_url) {
        ogImage = tweet.media.external.thumbnail_url;
      }
      if (!ogImage && ((_i = tweet.author) == null ? void 0 : _i.avatar_url)) {
        ogImage = tweet.author.avatar_url;
      }
      if (ogImage) {
        ogImage = await this.validateImageUrl(ogImage);
      }
      return {
        url: originalUrl,
        title: `${(_k = (_j = tweet.author) == null ? void 0 : _j.name) != null ? _k : screenName} (@${(_m = (_l = tweet.author) == null ? void 0 : _l.screen_name) != null ? _m : screenName})`,
        description: (_n = tweet.text) != null ? _n : null,
        ogImage,
        siteName: "X (Twitter)",
        favicon: (_p = (_o = tweet.author) == null ? void 0 : _o.avatar_url) != null ? _p : null,
        textContent: (_q = tweet.text) != null ? _q : ""
      };
    } catch (error) {
      console.warn(`fxtwitter scrape failed for ${originalUrl}:`, error);
      return this.createEmptyMetadata(originalUrl);
    }
  }
  /**
   * Extract meta tag content by property or name attribute
   */
  extractMeta(doc, property) {
    const propertyMeta = doc.querySelector(`meta[property="${property}"]`);
    if (propertyMeta) {
      return propertyMeta.getAttribute("content");
    }
    const nameMeta = doc.querySelector(`meta[name="${property}"]`);
    if (nameMeta) {
      return nameMeta.getAttribute("content");
    }
    return null;
  }
  /**
   * Extract title from og:title or title tag
   */
  extractTitle(doc) {
    const ogTitle = this.extractMeta(doc, "og:title");
    if (ogTitle) {
      return ogTitle;
    }
    const titleElement = doc.querySelector("title");
    if (titleElement && titleElement.textContent) {
      return titleElement.textContent.trim();
    }
    return null;
  }
  /**
   * Extract description from og:description or meta description
   */
  extractDescription(doc) {
    const ogDescription = this.extractMeta(doc, "og:description");
    if (ogDescription) {
      return ogDescription;
    }
    const description = this.extractMeta(doc, "description");
    if (description) {
      return description;
    }
    return null;
  }
  /**
   * Extract image from og:image or twitter:image, resolve relative URLs
   */
  extractImage(doc, baseUrl) {
    const ogImage = this.extractMeta(doc, "og:image");
    if (ogImage) {
      return this.resolveUrl(ogImage, baseUrl);
    }
    const twitterImage = this.extractMeta(doc, "twitter:image");
    if (twitterImage) {
      return this.resolveUrl(twitterImage, baseUrl);
    }
    return null;
  }
  /**
   * Extract text content from body, strip scripts/styles, limit length
   */
  extractTextContent(doc) {
    const body = doc.querySelector("body");
    if (!body) {
      return "";
    }
    const bodyClone = body.cloneNode(true);
    const selectorsToRemove = [
      "script",
      "style",
      "noscript",
      "iframe",
      "nav",
      "header",
      "footer",
      "aside",
      '[role="navigation"]',
      '[role="banner"]',
      '[role="contentinfo"]'
    ];
    selectorsToRemove.forEach((selector) => {
      bodyClone.querySelectorAll(selector).forEach((el) => el.remove());
    });
    let text = bodyClone.textContent || "";
    text = text.replace(/\s+/g, " ").replace(/\n\s*\n/g, "\n").trim();
    const maxLength = 1e4;
    if (text.length > maxLength) {
      text = text.substring(0, maxLength) + "...";
    }
    return text;
  }
  /**
   * Extract favicon URL and resolve to absolute URL
   */
  extractFavicon(doc, baseUrl) {
    const selectors = [
      'link[rel="icon"]',
      'link[rel="shortcut icon"]',
      'link[rel="apple-touch-icon"]'
    ];
    for (const selector of selectors) {
      const link = doc.querySelector(selector);
      if (link) {
        const href = link.getAttribute("href");
        if (href) {
          return this.resolveUrl(href, baseUrl);
        }
      }
    }
    return `${baseUrl}/favicon.ico`;
  }
  /**
   * Resolve relative URL to absolute URL
   */
  resolveUrl(relative, base) {
    try {
      if (relative.startsWith("http://") || relative.startsWith("https://")) {
        return relative;
      }
      if (relative.startsWith("//")) {
        const baseUrl = new URL(base);
        return `${baseUrl.protocol}${relative}`;
      }
      return new URL(relative, base).href;
    } catch (error) {
      console.warn("Error resolving URL:", error);
      return relative;
    }
  }
  /**
   * Validate that an image URL is accessible (HEAD request)
   */
  async validateImageUrl(imageUrl) {
    try {
      const response = await (0, import_obsidian5.requestUrl)({
        url: imageUrl,
        method: "HEAD",
        throw: false
      });
      return response.status === 200 ? imageUrl : null;
    } catch (e) {
      return null;
    }
  }
  /**
   * Create empty metadata object for failed scrapes
   */
  createEmptyMetadata(url) {
    return {
      url,
      title: null,
      description: null,
      ogImage: null,
      siteName: null,
      favicon: null,
      textContent: ""
    };
  }
};
_ScraperService.TWITTER_HOSTS = ["twitter.com", "www.twitter.com", "x.com", "www.x.com"];
_ScraperService.TWITTER_STATUS_RE = /\/([^/]+)\/status\/(\d+)/;
var ScraperService = _ScraperService;

// src/canvas/monitor.ts
var import_obsidian6 = require("obsidian");

// src/canvas/utils.ts
function isValidUrl(url) {
  try {
    const urlObj = new URL(url);
    return urlObj.protocol === "http:" || urlObj.protocol === "https:";
  } catch (e) {
    return false;
  }
}

// src/canvas/monitor.ts
var CanvasMonitor = class {
  constructor(app, onNewLinkNode) {
    this.app = app;
    this.onNewLinkNode = onNewLinkNode;
    this.seenNodes = /* @__PURE__ */ new Map();
    // canvasPath -> nodeIds
    this.initializedCanvases = /* @__PURE__ */ new Set();
    // canvases that have been scanned at least once
    this.modifyHandler = null;
  }
  startWatching() {
    if (this.modifyHandler) {
      this.app.vault.offref(this.modifyHandler);
    }
    this.modifyHandler = this.app.vault.on("modify", (file) => {
      if (file instanceof import_obsidian6.TFile && file.extension === "canvas") {
        void this.checkForNewLinks(file);
      }
    });
  }
  stopWatching() {
    if (this.modifyHandler) {
      this.app.vault.offref(this.modifyHandler);
      this.modifyHandler = null;
    }
    this.seenNodes.clear();
    this.initializedCanvases.clear();
  }
  async checkForNewLinks(file) {
    try {
      const content = await this.app.vault.read(file);
      const canvasData = JSON.parse(content);
      const canvasPath = file.path;
      const isFirstScan = !this.initializedCanvases.has(canvasPath);
      const previouslySeen = this.seenNodes.get(canvasPath) || /* @__PURE__ */ new Set();
      const currentNodes = /* @__PURE__ */ new Set();
      const linkNodes = canvasData.nodes.filter(
        (node) => node.type === "link"
      );
      for (const node of canvasData.nodes) {
        if (node.type === "text" && "text" in node) {
          const text = node.text.trim();
          if (isValidUrl(text)) {
            linkNodes.push({
              id: node.id,
              type: "link",
              url: text,
              x: node.x,
              y: node.y,
              width: node.width,
              height: node.height
            });
          }
        }
      }
      for (const node of linkNodes) {
        currentNodes.add(node.id);
        if (!isFirstScan && !previouslySeen.has(node.id)) {
          this.onNewLinkNode(file, node);
        }
      }
      this.seenNodes.set(canvasPath, currentNodes);
      if (isFirstScan) {
        this.initializedCanvases.add(canvasPath);
      }
    } catch (error) {
      console.error("Error checking for new links in canvas:", error);
    }
  }
  clearCache(canvasPath) {
    if (canvasPath) {
      this.seenNodes.delete(canvasPath);
      this.initializedCanvases.delete(canvasPath);
    } else {
      this.seenNodes.clear();
      this.initializedCanvases.clear();
    }
  }
};

// src/main.ts
var DetailedCanvasPlugin = class extends import_obsidian7.Plugin {
  constructor() {
    super(...arguments);
    this.processingNodes = /* @__PURE__ */ new Set();
  }
  // Prevent duplicate processing
  async onload() {
    console.log("[DetailedCanvas] Plugin loading, version:", this.manifest.version);
    await this.loadSettings();
    console.log("[DetailedCanvas] Provider:", this.settings.aiProvider, "| Auto-enrich:", this.settings.autoEnrichOnPaste);
    this.aiProvider = createProvider(this.settings);
    this.scraperService = new ScraperService();
    this.canvasMonitor = new CanvasMonitor(
      this.app,
      (file, node) => {
        void this.handleNewLinkNode(file, node);
      }
    );
    if (this.settings.autoEnrichOnPaste) {
      this.canvasMonitor.startWatching();
    }
    this.addCommand({
      id: "enrich-selected-link",
      name: "Enrich selected link card",
      checkCallback: (checking) => {
        const canvasView = this.getActiveCanvasView();
        if (!canvasView)
          return false;
        const selection = this.getSelectedLinkNodes(canvasView);
        if (selection.length === 0)
          return false;
        if (!checking) {
          void this.enrichSelectedLinks(canvasView);
        }
        return true;
      }
    });
    this.addCommand({
      id: "enrich-all-links",
      name: "Enrich all link cards in canvas",
      checkCallback: (checking) => {
        const canvasFile = this.getActiveCanvasFile();
        if (!canvasFile)
          return false;
        if (!checking) {
          void this.enrichAllLinksInCanvas(canvasFile);
        }
        return true;
      }
    });
    this.registerEvent(
      this.app.workspace.on("canvas:node-menu", (menu, node) => {
        var _a;
        const nodeData = (_a = node.getData) == null ? void 0 : _a.call(node);
        const isLinkNode = nodeData && nodeData.type === "link" && typeof nodeData.url === "string" && isValidUrl(nodeData.url);
        const isTextNodeWithUrl = nodeData && nodeData.type === "text" && "text" in nodeData && typeof nodeData.text === "string" && isValidUrl(nodeData.text.trim());
        if (isLinkNode || isTextNodeWithUrl) {
          menu.addItem((item) => {
            item.setTitle("Enrich with AI description").setIcon("sparkles").onClick(() => {
              const canvasFile = this.getActiveCanvasFile();
              if (canvasFile) {
                let linkData;
                if (nodeData.type === "link") {
                  linkData = nodeData;
                } else {
                  const textData = nodeData;
                  linkData = {
                    id: textData.id,
                    type: "link",
                    url: textData.text.trim(),
                    x: textData.x,
                    y: textData.y,
                    width: textData.width,
                    height: textData.height
                  };
                }
                void this.enrichLinkNode(canvasFile, linkData);
              }
            });
          });
        }
      })
    );
    this.addSettingTab(new DetailedCanvasSettingTab(this.app, this));
  }
  onunload() {
    var _a;
    (_a = this.canvasMonitor) == null ? void 0 : _a.stopWatching();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    var _a, _b;
    await this.saveData(this.settings);
    this.aiProvider = createProvider(this.settings);
    if (this.settings.autoEnrichOnPaste) {
      (_a = this.canvasMonitor) == null ? void 0 : _a.startWatching();
    } else {
      (_b = this.canvasMonitor) == null ? void 0 : _b.stopWatching();
    }
  }
  // Handle new link node from canvas monitor
  async handleNewLinkNode(file, node) {
    if (!this.settings.autoEnrichOnPaste)
      return;
    if (!isValidUrl(node.url))
      return;
    await this.enrichLinkNode(file, node);
  }
  // Main enrichment logic
  async enrichLinkNode(canvasFile, node) {
    const nodeKey = `${canvasFile.path}:${node.id}`;
    if (this.processingNodes.has(nodeKey)) {
      return { success: false, error: "Already processing" };
    }
    this.processingNodes.add(nodeKey);
    try {
      await this.updateCanvasNodeTextWithRetry(node.id, `Loading...

${node.url}`);
      if (this.settings.showNotifications) {
        new import_obsidian7.Notice(`Enriching: ${node.url}`);
      }
      const metadata = await this.scraperService.scrape(node.url);
      if (!metadata) {
        throw new Error("Failed to fetch URL content");
      }
      let aiDescription = "";
      try {
        aiDescription = await this.aiProvider.generate(
          this.settings.descriptionPrompt,
          metadata.textContent
        );
      } catch (err) {
        console.warn("AI generation failed, using metadata description:", err);
        aiDescription = metadata.description || "No description available.";
      }
      const title = metadata.title || new URL(node.url).hostname;
      const desc = aiDescription.substring(0, this.settings.maxDescriptionLength);
      const siteName = metadata.siteName || new URL(node.url).hostname;
      const imageLine = metadata.ogImage ? `![](${metadata.ogImage})

` : "";
      const cardText = `${imageLine}## [${title}](${node.url})

${desc}

*${siteName}*`;
      const updated = await this.updateCanvasNodeTextWithRetry(node.id, cardText);
      if (!updated) {
        throw new Error("Failed to update canvas node");
      }
      if (this.settings.showNotifications) {
        new import_obsidian7.Notice(`Enriched: ${title}`);
      }
      return { success: true };
    } catch (error) {
      const errorMsg = error instanceof Error ? error.message : String(error);
      console.error("Enrichment failed:", errorMsg);
      if (this.settings.showNotifications) {
        new import_obsidian7.Notice(`Enrichment failed: ${errorMsg}`);
      }
      return { success: false, error: errorMsg };
    } finally {
      this.processingNodes.delete(nodeKey);
    }
  }
  // Update a canvas node's text content directly through the internal API
  updateCanvasNodeText(nodeId, newText) {
    try {
      const view = this.getActiveCanvasView();
      if (!view || !("canvas" in view))
        return false;
      const canvas = view.canvas;
      if (!(canvas == null ? void 0 : canvas.nodes))
        return false;
      const canvasNode = canvas.nodes.get(nodeId);
      if (!canvasNode)
        return false;
      if (canvasNode.setText) {
        canvasNode.setText(newText);
      }
      if (canvas.requestSave) {
        canvas.requestSave();
      }
      return true;
    } catch (e) {
      return false;
    }
  }
  // Retry wrapper for updateCanvasNodeText (canvas internal state may lag behind file changes)
  async updateCanvasNodeTextWithRetry(nodeId, text, retries = 3) {
    for (let i = 0; i < retries; i++) {
      if (this.updateCanvasNodeText(nodeId, text)) {
        return true;
      }
      await new Promise((resolve) => setTimeout(resolve, 300));
    }
    return false;
  }
  // Enrich selected links in canvas view
  async enrichSelectedLinks(canvasView) {
    const selection = this.getSelectedLinkNodes(canvasView);
    const canvasFile = this.getActiveCanvasFile();
    if (!canvasFile || selection.length === 0)
      return;
    for (const node of selection) {
      await this.enrichLinkNode(canvasFile, node);
    }
  }
  // Enrich all link nodes in canvas
  async enrichAllLinksInCanvas(canvasFile) {
    var _a;
    const view = this.getActiveCanvasView();
    if (!view || !("canvas" in view)) {
      new import_obsidian7.Notice("No active canvas view");
      return;
    }
    const canvas = view.canvas;
    if (!(canvas == null ? void 0 : canvas.nodes)) {
      new import_obsidian7.Notice("No canvas nodes found");
      return;
    }
    const validLinks = [];
    for (const [, node] of canvas.nodes) {
      const data = (_a = node.getData) == null ? void 0 : _a.call(node);
      if (!data)
        continue;
      if (data.type === "link" && typeof data.url === "string" && isValidUrl(data.url)) {
        validLinks.push(data);
      } else if (data.type === "text" && typeof data.text === "string" && isValidUrl(data.text.trim())) {
        validLinks.push({
          id: data.id,
          type: "link",
          url: data.text.trim(),
          x: data.x,
          y: data.y,
          width: data.width,
          height: data.height
        });
      }
    }
    if (validLinks.length === 0) {
      new import_obsidian7.Notice("No link cards found in canvas");
      return;
    }
    new import_obsidian7.Notice(`Enriching ${validLinks.length} link cards...`);
    for (const node of validLinks) {
      await this.enrichLinkNode(canvasFile, node);
    }
    new import_obsidian7.Notice("Finished enriching all link cards");
  }
  // Helper: Get active canvas view
  getActiveCanvasView() {
    const view = this.app.workspace.getActiveViewOfType(import_obsidian7.ItemView);
    if ((view == null ? void 0 : view.getViewType()) === "canvas") {
      return view;
    }
    return null;
  }
  // Helper: Get active canvas file
  getActiveCanvasFile() {
    const view = this.getActiveCanvasView();
    if (!view)
      return null;
    if ("file" in view && view.file instanceof import_obsidian7.TFile) {
      return view.file;
    }
    return null;
  }
  // Helper: Get selected link nodes from canvas view
  getSelectedLinkNodes(canvasView) {
    var _a;
    try {
      if (!("canvas" in canvasView))
        return [];
      const { canvas } = canvasView;
      if (!(canvas == null ? void 0 : canvas.selection))
        return [];
      const selected = [];
      for (const node of canvas.selection) {
        const data = (_a = node.getData) == null ? void 0 : _a.call(node);
        if (!data)
          continue;
        if (data.type === "link" && typeof data.url === "string" && isValidUrl(data.url)) {
          selected.push(data);
        } else if (data.type === "text" && "text" in data && typeof data.text === "string" && isValidUrl(data.text.trim())) {
          const textData = data;
          selected.push({
            id: textData.id,
            type: "link",
            url: textData.text.trim(),
            x: textData.x,
            y: textData.y,
            width: textData.width,
            height: textData.height
          });
        }
      }
      return selected;
    } catch (e) {
      return [];
    }
  }
};
